// Стили модалки крафта (патч 265). Тёмная тема по образцу остальных модалок
// инвентаря; отдельных палитр не заводим — цвета редкостей придут своим слоем.
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)' },
  sheet: { flex: 1, backgroundColor: '#1a1d1a', paddingTop: 8 },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 8, gap: 8 },
  headerTitle: { color: '#e8e6d9', fontSize: 18, fontWeight: '700', flexShrink: 1 },
  headerSpacer: { flex: 1 },
  closeText: { color: '#c9c6b5', fontSize: 20, paddingHorizontal: 8 },
  backText: { color: '#c9c6b5', fontSize: 14, paddingRight: 8 },
  tabs: { flexDirection: 'row', paddingHorizontal: 12, gap: 6, paddingBottom: 8 },
  tab: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8, backgroundColor: '#2a2e2a' },
  tabActive: { backgroundColor: '#3f4a3a' },
  tabText: { color: '#c9c6b5', fontSize: 12 },
  tabTextActive: { color: '#ffe9a8', fontWeight: '700' },
  list: { flex: 1, paddingHorizontal: 12 },
  row: { paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#2a2e2a' },
  rowDisabled: { opacity: 0.55 },
  rowTop: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  rowName: { color: '#e8e6d9', fontSize: 15, fontWeight: '600', flex: 1 },
  rowMeta: { color: '#8f9a86', fontSize: 12, marginTop: 2 },
  rowReason: { color: '#c76e6e', fontSize: 12, marginTop: 2 },
  rowReady: { color: '#7da769', fontSize: 12, marginTop: 2 },
  craftBtn: { backgroundColor: '#3f4a3a', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6 },
  craftBtnText: { color: '#ffe9a8', fontSize: 12, fontWeight: '700' },
  detailSection: { marginTop: 10 },
  detailLabel: { color: '#8f9a86', fontSize: 12, marginBottom: 4, textTransform: 'uppercase' },
  materialLine: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 3 },
  materialName: { color: '#e8e6d9', fontSize: 13, flex: 1 },
  materialOk: { color: '#7da769', fontSize: 12 },
  materialBad: { color: '#c76e6e', fontSize: 12 },
  qtyRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 12 },
  qtyBtn: { borderWidth: 1, borderColor: '#3f4a3a', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 4 },
  qtyBtnText: { color: '#ffe9a8', fontSize: 16 },
  qtyValue: { color: '#e8e6d9', fontSize: 15, minWidth: 24, textAlign: 'center' },
  bigCraft: { backgroundColor: '#3f4a3a', borderRadius: 10, padding: 12, marginTop: 14, alignItems: 'center' },
  bigCraftDisabled: { opacity: 0.5 },
  bigCraftText: { color: '#ffe9a8', fontSize: 15, fontWeight: '700' },
  resultBox: { backgroundColor: '#141714', borderRadius: 10, padding: 12, marginTop: 12 },
  resultLine: { color: '#e8e6d9', fontSize: 13, lineHeight: 19 },
  doneBtn: { backgroundColor: '#2a2e2a', borderRadius: 10, padding: 10, marginTop: 12, alignItems: 'center' },
  doneBtnText: { color: '#c9c6b5', fontSize: 14 },
  empty: { color: '#8f9a86', fontSize: 13, textAlign: 'center', marginTop: 30 },
});
