// Стили окна фильтров снаряжения (патч 429): шапка с крестиком, лист —
// чекбоксы категорий по 3 в ряд («квадраты по 3 в ряд»), параметры групп,
// кнопка «Показать (N)» внизу. Шапка, низ и содержимое — по скролл-закону.
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  overlay: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.5)', justifyContent: 'flex-end' },
  sheet: { backgroundColor: 'white', borderTopLeftRadius: 14, borderTopRightRadius: 14, height: '85%' },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#ddd' },
  headerTitle: { fontSize: 17, fontWeight: 'bold', color: '#333' },
  closeButton: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#eee', alignItems: 'center', justifyContent: 'center' },
  closeIcon: { fontSize: 16, color: '#333' },
  body: { flex: 1 },
  bodyContent: { paddingHorizontal: 14, paddingTop: 10, paddingBottom: 16 },
  footer: { paddingHorizontal: 16, paddingVertical: 10, borderTopWidth: 1, borderTopColor: '#ddd' },
  showButton: { backgroundColor: '#2f6df6', borderRadius: 8, paddingVertical: 12, alignItems: 'center' },
  showButtonText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  kindsRow: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 8 },
  kindBox: { width: '31%', marginRight: '2%', marginBottom: 6, flexDirection: 'row', alignItems: 'center', paddingVertical: 6, paddingHorizontal: 4, borderRadius: 6 },
  kindBoxOn: { backgroundColor: '#e8f0fe' },
  kindCheck: { fontSize: 15, marginRight: 4, color: '#333' },
  kindName: { fontSize: 12, color: '#333', flex: 1 },
  kindNameOn: { color: '#2f6df6', fontWeight: 'bold' },
  sectionTitle: { fontSize: 13, fontWeight: 'bold', color: '#555', marginTop: 8, marginBottom: 4 },
  row: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', marginBottom: 6 },
  rowLabel: { fontSize: 13, color: '#333', width: 120 },
  rangeInput: { borderBottomWidth: 1, borderColor: '#bbb', width: 56, textAlign: 'center', paddingVertical: 2, fontSize: 14, color: '#333', marginHorizontal: 4 },
  rangeDash: { fontSize: 13, color: '#777' },
  chip: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12, borderWidth: 1, borderColor: '#999', marginRight: 6, marginBottom: 4 },
  chipOn: { backgroundColor: '#2f6df6', borderColor: '#2f6df6' },
  chipText: { fontSize: 12, color: '#333' },
  chipTextOn: { color: '#fff' },
  dropdownHeader: { flexDirection: 'row', alignItems: 'center', paddingVertical: 5 },
  dropdownArrow: { fontSize: 11, color: '#555', marginRight: 6 },
  dropdownTitle: { fontSize: 13, color: '#333' },
  dropdownCount: { fontSize: 12, color: '#2f6df6', marginLeft: 6 },
  optionRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 3, paddingLeft: 18 },
  optionText: { fontSize: 12, color: '#333', flex: 1 },
  resetButton: { alignSelf: 'center', marginTop: 10, paddingHorizontal: 16, paddingVertical: 6, borderRadius: 8, backgroundColor: '#eee', borderWidth: 1, borderColor: '#bbb' },
  resetText: { fontSize: 13, color: '#333' },
});
