export type ChemDuration = 'instant' | 'brief' | 'lasting';

export interface Chem {
  name: string;
  value: number;
  rarity: number;
  weight: number;
  duration: ChemDuration;
  addictive: boolean;
  addictionLevel?: number; // 1, 2, or 3
  effectKey: string; // i18n key for effect description
}

export const chems: Chem[] = [
  // ===== MEDICAL =====
  {
    name: 'Addictol',
    value: 125,
    rarity: 3,
    weight: 0.5,
    duration: 'instant',
    addictive: false,
    effectKey: 'itemEffects.chems.addictol',
  },
  {
    name: 'Antibiotics',
    value: 75,
    rarity: 3,
    weight: 0.5,
    duration: 'instant',
    addictive: false,
    effectKey: 'itemEffects.chems.antibiotics',
  },
  {
    name: 'Healing Salve',
    value: 20,
    rarity: 1,
    weight: 0.5,
    duration: 'instant',
    addictive: false,
    effectKey: 'itemEffects.chems.healingSalve',
  },
  {
    name: 'Skeeto Spit',
    value: 40,
    rarity: 2,
    weight: 0.5,
    duration: 'lasting',
    addictive: false,
    effectKey: 'itemEffects.chems.skeetoSpit',
  },
  {
    name: 'Stimpak',
    value: 50,
    rarity: 2,
    weight: 0.5,
    duration: 'instant',
    addictive: false,
    effectKey: 'itemEffects.chems.stimpak',
  },
  {
    name: 'Stimpak (Diluted)',
    value: 30,
    rarity: 1,
    weight: 0.5,
    duration: 'instant',
    addictive: false,
    effectKey: 'itemEffects.chems.stimpakDiluted',
  },
  {
    name: 'Super Stimpak',
    value: 90,
    rarity: 4,
    weight: 0.5,
    duration: 'instant',
    addictive: false,
    effectKey: 'itemEffects.chems.superStimpak',
  },
  {
    name: 'RadAway',
    value: 80,
    rarity: 2,
    weight: 0.5,
    duration: 'instant',
    addictive: false,
    effectKey: 'itemEffects.chems.radAway',
  },
  {
    name: 'RadAway (Diluted)',
    value: 50,
    rarity: 1,
    weight: 0.5,
    duration: 'instant',
    addictive: false,
    effectKey: 'itemEffects.chems.radAwayDiluted',
  },
  {
    name: 'Rad-X',
    value: 40,
    rarity: 2,
    weight: 0.5,
    duration: 'lasting',
    addictive: false,
    effectKey: 'itemEffects.chems.radX',
  },
  {
    name: 'Rad-X (Diluted)',
    value: 25,
    rarity: 1,
    weight: 0.5,
    duration: 'lasting',
    addictive: false,
    effectKey: 'itemEffects.chems.radXDiluted',
  },

  // ===== COMBAT DRUGS =====
  {
    name: 'Buffjet',
    value: 75,
    rarity: 4,
    weight: 0.5,
    duration: 'brief',
    addictive: true,
    addictionLevel: 1,
    effectKey: 'itemEffects.chems.buffjet',
  },
  {
    name: 'Buffout',
    value: 45,
    rarity: 2,
    weight: 0.5,
    duration: 'lasting',
    addictive: true,
    addictionLevel: 2,
    effectKey: 'itemEffects.chems.buffout',
  },
  {
    name: 'Bufftats',
    value: 75,
    rarity: 4,
    weight: 0.5,
    duration: 'lasting',
    addictive: true,
    addictionLevel: 1,
    effectKey: 'itemEffects.chems.bufftats',
  },
  {
    name: 'Calmex',
    value: 100,
    rarity: 4,
    weight: 0.5,
    duration: 'lasting',
    addictive: true,
    addictionLevel: 1,
    effectKey: 'itemEffects.chems.calmex',
  },
  {
    name: 'Daddy-O',
    value: 50,
    rarity: 2,
    weight: 0.5,
    duration: 'lasting',
    addictive: true,
    addictionLevel: 1,
    effectKey: 'itemEffects.chems.daddyO',
  },
  {
    name: 'Day Tripper',
    value: 40,
    rarity: 3,
    weight: 0.5,
    duration: 'lasting',
    addictive: true,
    addictionLevel: 1,
    effectKey: 'itemEffects.chems.dayTripper',
  },
  {
    name: 'Fury',
    value: 30,
    rarity: 4,
    weight: 0.5,
    duration: 'lasting',
    addictive: true,
    addictionLevel: 1,
    effectKey: 'itemEffects.chems.fury',
  },
  {
    name: 'Jet',
    value: 50,
    rarity: 2,
    weight: 0.5,
    duration: 'brief',
    addictive: true,
    addictionLevel: 2,
    effectKey: 'itemEffects.chems.jet',
  },
  {
    name: 'Jet Fuel',
    value: 60,
    rarity: 3,
    weight: 0.5,
    duration: 'lasting',
    addictive: true,
    addictionLevel: 1,
    effectKey: 'itemEffects.chems.jetFuel',
  },
  {
    name: 'Med-X',
    value: 50,
    rarity: 2,
    weight: 0.5,
    duration: 'lasting',
    addictive: true,
    addictionLevel: 2,
    effectKey: 'itemEffects.chems.medX',
  },
  {
    name: 'Mentats',
    value: 50,
    rarity: 2,
    weight: 0.5,
    duration: 'lasting',
    addictive: true,
    addictionLevel: 3,
    effectKey: 'itemEffects.chems.mentats',
  },
  {
    name: 'Berry Mentats',
    value: 60,
    rarity: 3,
    weight: 0.5,
    duration: 'lasting',
    addictive: true,
    addictionLevel: 2,
    effectKey: 'itemEffects.chems.berryMentats',
  },
  {
    name: 'Orange Mentats',
    value: 60,
    rarity: 3,
    weight: 0.5,
    duration: 'lasting',
    addictive: true,
    addictionLevel: 2,
    effectKey: 'itemEffects.chems.orangeMentats',
  },
  {
    name: 'Grape Mentats',
    value: 60,
    rarity: 3,
    weight: 0.5,
    duration: 'lasting',
    addictive: true,
    addictionLevel: 2,
    effectKey: 'itemEffects.chems.grapeMentats',
  },
  {
    name: 'Overdrive',
    value: 55,
    rarity: 3,
    weight: 0.5,
    duration: 'lasting',
    addictive: true,
    addictionLevel: 1,
    effectKey: 'itemEffects.chems.overdrive',
  },
  {
    name: 'Psycho',
    value: 50,
    rarity: 2,
    weight: 0.5,
    duration: 'lasting',
    addictive: true,
    addictionLevel: 2,
    effectKey: 'itemEffects.chems.psycho',
  },
  {
    name: 'Psychobuff',
    value: 70,
    rarity: 4,
    weight: 0.5,
    duration: 'lasting',
    addictive: true,
    addictionLevel: 1,
    effectKey: 'itemEffects.chems.psychobuff',
  },
  {
    name: 'Psycho Jet',
    value: 70,
    rarity: 4,
    weight: 0.5,
    duration: 'brief',
    addictive: true,
    addictionLevel: 1,
    effectKey: 'itemEffects.chems.psychoJet',
  },
  {
    name: 'Psychotats',
    value: 70,
    rarity: 4,
    weight: 0.5,
    duration: 'lasting',
    addictive: true,
    addictionLevel: 1,
    effectKey: 'itemEffects.chems.psychotats',
  },
  {
    name: 'Ultra Jet',
    value: 67,
    rarity: 2,
    weight: 0.5,
    duration: 'brief',
    addictive: true,
    addictionLevel: 3,
    effectKey: 'itemEffects.chems.ultraJet',
  },
  {
    name: 'X-Cell',
    value: 60,
    rarity: 4,
    weight: 0.5,
    duration: 'lasting',
    addictive: true,
    addictionLevel: 1,
    effectKey: 'itemEffects.chems.xCell',
  },
];
