export interface FoodItem {
  name: string;
  hpHealed: number;
  value: number;
  rarity: number;
  weight: number;
  type: 'food' | 'drink';
  irradiated: boolean;
  effectKey?: string; // i18n key for effect description
}

export const food: FoodItem[] = [
  // ===== NOURRITURE =====
  { name: 'Fancy Lads Snack Cakes', hpHealed: 3, value: 18, rarity: 0, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Silt Bean', hpHealed: 3, value: 5, rarity: 1, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Noodle Cup', hpHealed: 6, value: 20, rarity: 2, weight: 0.5, type: 'food', irradiated: false },
  { name: 'Sugar Bombs', hpHealed: 4, value: 11, rarity: 0, weight: 0.5, type: 'food', irradiated: true, effectKey: 'itemEffects.food.sugarBombs' },
  { name: 'Squirrel Bits', hpHealed: 4, value: 4, rarity: 1, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Crispy Squirrel Bits', hpHealed: 6, value: 6, rarity: 2, weight: 0.5, type: 'food', irradiated: false },
  { name: 'Gum Drops', hpHealed: 3, value: 5, rarity: 0, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Squirrel on a Stick', hpHealed: 7, value: 15, rarity: 2, weight: 0.5, type: 'food', irradiated: false },
  { name: 'Iguana on a Stick', hpHealed: 6, value: 33, rarity: 2, weight: 0.5, type: 'food', irradiated: false },
  { name: 'Carrot', hpHealed: 3, value: 3, rarity: 1, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Radroach Meat', hpHealed: 4, value: 3, rarity: 0, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Potato Crisps', hpHealed: 3, value: 7, rarity: 0, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Yao Guai Ribs', hpHealed: 13, value: 90, rarity: 4, weight: 0.5, type: 'food', irradiated: false, effectKey: 'itemEffects.food.yaoGuaiRibs' },
  { name: 'Dog Ribs', hpHealed: 6, value: 12, rarity: 1, weight: 0.5, type: 'food', irradiated: false },
  { name: 'Mutant Hound Ribs', hpHealed: 8, value: 12, rarity: 3, weight: 0.5, type: 'food', irradiated: false, effectKey: 'itemEffects.food.mutantHoundRibs' },
  { name: 'Gourd', hpHealed: 3, value: 6, rarity: 1, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Cram', hpHealed: 5, value: 25, rarity: 1, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Corn', hpHealed: 3, value: 6, rarity: 1, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Brain Fungus', hpHealed: 3, value: 6, rarity: 1, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Ribeye Steak', hpHealed: 10, value: 40, rarity: 2, weight: 0.5, type: 'food', irradiated: false },
  { name: 'Deathclaw Filet', hpHealed: 11, value: 35, rarity: 3, weight: 0.5, type: 'food', irradiated: false, effectKey: 'itemEffects.food.deathclawFilet' },
  { name: 'Mutfruit', hpHealed: 3, value: 8, rarity: 0, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Tarberry', hpHealed: 3, value: 5, rarity: 3, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Canned Bean', hpHealed: 3, value: 6, rarity: 1, weight: 0.5, type: 'food', irradiated: true },
  { name: 'BlamCo Mac and Cheese', hpHealed: 4, value: 10, rarity: 1, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Melon', hpHealed: 3, value: 6, rarity: 1, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Grilled Bloatfly', hpHealed: 6, value: 15, rarity: 1, weight: 0.5, type: 'food', irradiated: false, effectKey: 'itemEffects.food.grilledBloatfly' },
  { name: 'Deathclaw Egg', hpHealed: 7, value: 69, rarity: 3, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Mirelurk Egg', hpHealed: 3, value: 0, rarity: 2, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Radscorpion Egg', hpHealed: 6, value: 48, rarity: 3, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Yum Yum Deviled Eggs', hpHealed: 4, value: 20, rarity: 0, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Deathclaw Omelette', hpHealed: 11, value: 80, rarity: 4, weight: 0.5, type: 'food', irradiated: false, effectKey: 'itemEffects.food.deathclawOmelette' },
  { name: 'Mirelurk Egg Omelette', hpHealed: 7, value: 30, rarity: 3, weight: 0.5, type: 'food', irradiated: false, effectKey: 'itemEffects.food.mirelurkEggOmelette' },
  { name: 'Radscorpion Egg Omelette', hpHealed: 9, value: 65, rarity: 4, weight: 0.5, type: 'food', irradiated: false, effectKey: 'itemEffects.food.radscorpionEggOmelette' },
  { name: 'Institute Food Packet', hpHealed: 5, value: 10, rarity: 2, weight: 0.5, type: 'food', irradiated: false },
  { name: 'Sweet Roll', hpHealed: 4, value: 9, rarity: 1, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Food Paste', hpHealed: 7, value: 0, rarity: 2, weight: 0.5, type: 'food', irradiated: false, effectKey: 'itemEffects.food.foodPaste' },
  { name: 'Mirelurk Paste', hpHealed: 12, value: 35, rarity: 3, weight: 0.5, type: 'food', irradiated: false, effectKey: 'itemEffects.food.mirelurkPaste' },
  { name: 'Dog Food', hpHealed: 3, value: 6, rarity: 0, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Potato', hpHealed: 3, value: 7, rarity: 1, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Dandy Boy Apples', hpHealed: 3, value: 7, rarity: 0, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Pork n Beans', hpHealed: 4, value: 10, rarity: 0, weight: 0.5, type: 'food', irradiated: true },
  { name: 'InstaMash', hpHealed: 4, value: 20, rarity: 0, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Grilled Radroach', hpHealed: 5, value: 7, rarity: 1, weight: 0.5, type: 'food', irradiated: false },
  { name: 'Grilled Radstag', hpHealed: 11, value: 60, rarity: 2, weight: 0.5, type: 'food', irradiated: false, effectKey: 'itemEffects.food.grilledRadstag' },
  { name: 'Squirrel Stew', hpHealed: 10, value: 24, rarity: 2, weight: 0.5, type: 'food', irradiated: false },
  { name: 'Radstag Stew', hpHealed: 12, value: 60, rarity: 3, weight: 0.5, type: 'food', irradiated: false, effectKey: 'itemEffects.food.radstag_Stew' },
  { name: 'Iguana Stew', hpHealed: 4, value: 8, rarity: 1, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Yao Guai Roast', hpHealed: 14, value: 110, rarity: 4, weight: 0.5, type: 'food', irradiated: false, effectKey: 'itemEffects.food.yaoGuaiRoast' },
  { name: 'Vegetable Soup', hpHealed: 7, value: 13, rarity: 2, weight: 0.5, type: 'food', irradiated: false, effectKey: 'itemEffects.food.vegetableSoup' },
  { name: 'Iguana Soup', hpHealed: 10, value: 21, rarity: 3, weight: 0.5, type: 'food', irradiated: false },
  { name: 'Deathclaw Steak', hpHealed: 14, value: 130, rarity: 4, weight: 0.5, type: 'food', irradiated: false, effectKey: 'itemEffects.food.deathclawSteak' },
  { name: 'Radscorpion Steak', hpHealed: 12, value: 65, rarity: 3, weight: 0.5, type: 'food', irradiated: false, effectKey: 'itemEffects.food.radscorpionSteak' },
  { name: 'Mole Rat Steak', hpHealed: 7, value: 8, rarity: 1, weight: 0.5, type: 'food', irradiated: false, effectKey: 'itemEffects.food.moleRatSteak' },
  { name: 'Mirelurk Queen Steak', hpHealed: 14, value: 130, rarity: 5, weight: 0.5, type: 'food', irradiated: false, effectKey: 'itemEffects.food.mirelurkQueenSteak' },
  { name: 'Stingwing Steak', hpHealed: 10, value: 18, rarity: 2, weight: 0.5, type: 'food', irradiated: false, effectKey: 'itemEffects.food.stingwingSteak' },
  { name: 'Salisbury Steak', hpHealed: 5, value: 20, rarity: 0, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Perfectly Preserved Pie', hpHealed: 5, value: 20, rarity: 3, weight: 0.5, type: 'food', irradiated: false },
  { name: 'Stray Dog Meat', hpHealed: 3, value: 28, rarity: 1, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Deathclaw Meat', hpHealed: 8, value: 30, rarity: 1, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Deathclaw Steak Cooked', hpHealed: 9, value: 110, rarity: 3, weight: 0.5, type: 'food', irradiated: false },
  { name: 'Mirelurk Meat', hpHealed: 6, value: 18, rarity: 1, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Softshell Mirelurk Meat', hpHealed: 6, value: 22, rarity: 2, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Grilled Mirelurk Meat', hpHealed: 9, value: 40, rarity: 3, weight: 0.5, type: 'food', irradiated: false, effectKey: 'itemEffects.food.grilledMirelurkMeat' },
  { name: 'Roasted Mirelurk Meat', hpHealed: 8, value: 40, rarity: 2, weight: 0.5, type: 'food', irradiated: false, effectKey: 'itemEffects.food.roastedMirelurkMeat' },
  { name: 'Mutant Hound Meat', hpHealed: 5, value: 8, rarity: 2, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Bloatfly Meat', hpHealed: 2, value: 8, rarity: 0, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Radstag Meat', hpHealed: 8, value: 50, rarity: 1, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Radscorpion Meat', hpHealed: 9, value: 55, rarity: 2, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Mole Rat Meat', hpHealed: 5, value: 5, rarity: 0, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Queen Mirelurk Meat', hpHealed: 10, value: 22, rarity: 4, weight: 0.5, type: 'food', irradiated: true, effectKey: 'itemEffects.food.queenMirelurkMeat' },
  { name: 'Stingwing Meat', hpHealed: 7, value: 8, rarity: 1, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Yao Guai Meat', hpHealed: 9, value: 85, rarity: 3, weight: 0.5, type: 'food', irradiated: true },
  { name: 'Canned Meat', hpHealed: 6, value: 25, rarity: 0, weight: 0.5, type: 'food', irradiated: true, effectKey: 'itemEffects.food.cannedMeat' },

  // ===== BOISSONS =====
  { name: 'Beer', hpHealed: 0, value: 5, rarity: 1, weight: 0.5, type: 'drink', irradiated: false, effectKey: 'itemEffects.drinks.beer' },
  { name: 'Refreshing Beverage', hpHealed: 11, value: 110, rarity: 5, weight: 0.5, type: 'drink', irradiated: false, effectKey: 'itemEffects.drinks.refreshingBeverage' },
  { name: 'Bourbon', hpHealed: 0, value: 7, rarity: 2, weight: 0.5, type: 'drink', irradiated: false, effectKey: 'itemEffects.drinks.bourbon' },
  { name: 'Moonshine', hpHealed: 0, value: 30, rarity: 3, weight: 0.5, type: 'drink', irradiated: false, effectKey: 'itemEffects.drinks.moonshine' },
  { name: 'Purified Water', hpHealed: 3, value: 20, rarity: 1, weight: 0.5, type: 'drink', irradiated: false },
  { name: 'Dirty Water', hpHealed: 2, value: 5, rarity: 0, weight: 0.5, type: 'drink', irradiated: true },
  { name: 'Dirty Wastelander', hpHealed: 0, value: 10, rarity: 3, weight: 0.5, type: 'drink', irradiated: false, effectKey: 'itemEffects.drinks.dirtyWastelander' },
  { name: 'Mutfruit Juice', hpHealed: 3, value: 8, rarity: 2, weight: 0.5, type: 'drink', irradiated: false, effectKey: 'itemEffects.drinks.mutfruitJuice' },
  { name: 'Tarberry Juice', hpHealed: 3, value: 5, rarity: 4, weight: 0.5, type: 'drink', irradiated: false, effectKey: 'itemEffects.drinks.tarberryJuice' },
  { name: 'Melon Juice', hpHealed: 3, value: 6, rarity: 2, weight: 0.5, type: 'drink', irradiated: false, effectKey: 'itemEffects.drinks.melonJuice' },
  { name: 'Potato Juice', hpHealed: 3, value: 7, rarity: 3, weight: 0.5, type: 'drink', irradiated: false, effectKey: 'itemEffects.drinks.potatoJuice' },
  { name: 'Brahmin Milk', hpHealed: 1, value: 15, rarity: 2, weight: 0.5, type: 'drink', irradiated: false, effectKey: 'itemEffects.drinks.brahminMilk' },
  { name: 'Nuka-Cherry', hpHealed: 3, value: 40, rarity: 3, weight: 0.5, type: 'drink', irradiated: true, effectKey: 'itemEffects.drinks.nukaCherry' },
  { name: 'Nuka-Cola', hpHealed: 2, value: 20, rarity: 2, weight: 0.5, type: 'drink', irradiated: true, effectKey: 'itemEffects.drinks.nukaCola' },
  { name: 'Nuka-Cola Quantum', hpHealed: 10, value: 50, rarity: 5, weight: 0.5, type: 'drink', irradiated: true, effectKey: 'itemEffects.drinks.nukaColaQuantum' },
  { name: 'Blood Pack', hpHealed: 3, value: 10, rarity: 2, weight: 0.5, type: 'drink', irradiated: false },
  { name: 'Glowing Blood Pack', hpHealed: 4, value: 30, rarity: 3, weight: 0.5, type: 'drink', irradiated: false, effectKey: 'itemEffects.drinks.glowingBloodPack' },
  { name: 'Rum', hpHealed: 0, value: 8, rarity: 2, weight: 0.5, type: 'drink', irradiated: false, effectKey: 'itemEffects.drinks.rum' },
  { name: 'Irradiated Blood', hpHealed: 3, value: 50, rarity: 2, weight: 0.5, type: 'drink', irradiated: true, effectKey: 'itemEffects.drinks.irradiatedBlood' },
  { name: 'Wine', hpHealed: 0, value: 5, rarity: 3, weight: 0.5, type: 'drink', irradiated: false, effectKey: 'itemEffects.drinks.wine' },
  { name: 'Vodka', hpHealed: 2, value: 5, rarity: 3, weight: 0.5, type: 'drink', irradiated: false, effectKey: 'itemEffects.drinks.vodka' },
  { name: 'Whiskey', hpHealed: 0, value: 5, rarity: 3, weight: 0.5, type: 'drink', irradiated: false, effectKey: 'itemEffects.drinks.whiskey' },
];
