import type { Weapon } from './types';

export const weapons: Weapon[] = [
  // ===== ARMES LÉGÈRES (Small Guns) =====
  {
    name: '.44 Pistol',
    value: 99,
    rarity: 2,
    weight: 2,
    skill: 'smallGuns',
    damage: 6,
    damageType: 'physical',
    fireRate: 1,
    range: 'close',
    qualities: [{ quality: 'vicious' }, { quality: 'closeQuarters' }],
    ammo: '.44',
  },
  {
    name: '10mm Pistol',
    value: 50,
    rarity: 1,
    weight: 2,
    skill: 'smallGuns',
    damage: 4,
    damageType: 'physical',
    fireRate: 2,
    range: 'close',
    qualities: [{ quality: 'closeQuarters' }, { quality: 'reliable' }],
    ammo: '10mm',
  },
  {
    name: 'Flare Gun',
    value: 50,
    rarity: 1,
    weight: 1,
    skill: 'smallGuns',
    damage: 3,
    damageType: 'physical',
    fireRate: 0,
    range: 'medium',
    qualities: [{ quality: 'reliable' }],
    ammo: 'flare',
  },
  {
    name: 'Assault Rifle',
    value: 144,
    rarity: 2,
    weight: 6.5,
    skill: 'smallGuns',
    damage: 5,
    damageType: 'physical',
    fireRate: 2,
    range: 'medium',
    qualities: [{ quality: 'twoHanded' }],
    ammo: '5.56mm',
  },
  {
    name: 'Combat Rifle',
    value: 117,
    rarity: 2,
    weight: 5.5,
    skill: 'smallGuns',
    damage: 5,
    damageType: 'physical',
    fireRate: 2,
    range: 'medium',
    qualities: [{ quality: 'twoHanded' }],
    ammo: '.45',
  },
  {
    name: 'Gauss Rifle',
    value: 228,
    rarity: 4,
    weight: 8,
    skill: 'smallGuns',
    damage: 10,
    damageType: 'physical',
    fireRate: 1,
    range: 'long',
    qualities: [{ quality: 'piercing', value: 1 }, { quality: 'twoHanded' }],
    ammo: '2mmEC',
  },
  {
    name: 'Hunting Rifle',
    value: 55,
    rarity: 2,
    weight: 5,
    skill: 'smallGuns',
    damage: 6,
    damageType: 'physical',
    fireRate: 0,
    range: 'medium',
    qualities: [{ quality: 'piercing', value: 1 }, { quality: 'twoHanded' }],
    ammo: '.308',
  },
  {
    name: 'Submachine Gun',
    value: 109,
    rarity: 1,
    weight: 6,
    skill: 'smallGuns',
    damage: 3,
    damageType: 'physical',
    fireRate: 3,
    range: 'close',
    qualities: [{ quality: 'burst' }, { quality: 'twoHanded' }, { quality: 'inaccurate' }],
    ammo: '.45',
  },
  {
    name: 'Combat Shotgun',
    value: 87,
    rarity: 2,
    weight: 5.5,
    skill: 'smallGuns',
    damage: 5,
    damageType: 'physical',
    fireRate: 2,
    range: 'close',
    qualities: [{ quality: 'spread' }, { quality: 'twoHanded' }, { quality: 'inaccurate' }],
    ammo: 'shotgunShell',
  },
  {
    name: 'Double-Barrel Shotgun',
    value: 39,
    rarity: 1,
    weight: 4.5,
    skill: 'smallGuns',
    damage: 5,
    damageType: 'physical',
    fireRate: 1,
    range: 'close',
    qualities: [{ quality: 'vicious' }, { quality: 'spread' }, { quality: 'twoHanded' }, { quality: 'inaccurate' }],
    ammo: 'shotgunShell',
  },
  {
    name: 'Pipe Bolt-Action',
    value: 30,
    rarity: 0,
    weight: 1.5,
    skill: 'smallGuns',
    damage: 5,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [{ quality: 'piercing', value: 1 }, { quality: 'unreliable' }],
    ammo: '.308',
  },
  {
    name: 'Pipe Gun',
    value: 30,
    rarity: 0,
    weight: 1,
    skill: 'smallGuns',
    damage: 3,
    damageType: 'physical',
    fireRate: 2,
    range: 'close',
    qualities: [{ quality: 'closeQuarters' }, { quality: 'unreliable' }],
    ammo: '.38',
  },
  {
    name: 'Pipe Revolver',
    value: 25,
    rarity: 0,
    weight: 2,
    skill: 'smallGuns',
    damage: 4,
    damageType: 'physical',
    fireRate: 1,
    range: 'close',
    qualities: [{ quality: 'closeQuarters' }, { quality: 'unreliable' }],
    ammo: '.45',
  },
  {
    name: 'Railway Rifle',
    value: 290,
    rarity: 4,
    weight: 7,
    skill: 'smallGuns',
    damage: 10,
    damageType: 'physical',
    fireRate: 0,
    range: 'medium',
    qualities: [{ quality: 'breaking' }, { quality: 'twoHanded' }, { quality: 'unreliable' }, { quality: 'debilitating' }],
    ammo: 'railwaySpike',
  },
  {
    name: 'Syringer',
    value: 132,
    rarity: 2,
    weight: 3,
    skill: 'smallGuns',
    damage: 3,
    damageType: 'physical',
    fireRate: 0,
    range: 'medium',
    qualities: [{ quality: 'twoHanded' }],
    ammo: 'syringerAmmo',
  },

  // ===== ARMES À ÉNERGIE (Energy Weapons) =====
  {
    name: 'Institute Laser',
    value: 50,
    rarity: 2,
    weight: 2,
    skill: 'energyWeapons',
    damage: 3,
    damageType: 'energy',
    fireRate: 3,
    range: 'close',
    qualities: [{ quality: 'burst' }, { quality: 'closeQuarters' }, { quality: 'inaccurate' }],
    ammo: 'fusionCell',
  },
  {
    name: 'Laser Musket',
    value: 57,
    rarity: 1,
    weight: 6.5,
    skill: 'energyWeapons',
    damage: 5,
    damageType: 'energy',
    fireRate: 0,
    range: 'medium',
    qualities: [{ quality: 'piercing', value: 1 }, { quality: 'twoHanded' }],
    ammo: 'fusionCell',
  },
  {
    name: 'Laser Pistol',
    value: 69,
    rarity: 2,
    weight: 2,
    skill: 'energyWeapons',
    damage: 4,
    damageType: 'energy',
    fireRate: 2,
    range: 'close',
    qualities: [{ quality: 'piercing', value: 1 }, { quality: 'closeQuarters' }],
    ammo: 'fusionCell',
  },
  {
    name: 'Plasma Pistol',
    value: 123,
    rarity: 3,
    weight: 2,
    skill: 'energyWeapons',
    damage: 6,
    damageType: 'energy',
    fireRate: 1,
    range: 'close',
    qualities: [{ quality: 'closeQuarters' }],
    ammo: 'plasmaCartridge',
  },
  {
    name: 'Gamma Gun',
    value: 156,
    rarity: 5,
    weight: 1.5,
    skill: 'energyWeapons',
    damage: 3,
    damageType: 'radiation',
    fireRate: 1,
    range: 'medium',
    qualities: [{ quality: 'stun' }, { quality: 'piercing', value: 1 }, { quality: 'inaccurate' }, { quality: 'blast' }],
    ammo: 'gammaRound',
  },

  // ===== ARMES LOURDES (Big Guns) =====
  {
    name: 'Fat Man',
    value: 512,
    rarity: 4,
    weight: 15.5,
    skill: 'bigGuns',
    damage: 21,
    damageType: 'physical',
    fireRate: 0,
    range: 'medium',
    qualities: [{ quality: 'vicious' }, { quality: 'breaking' }, { quality: 'radioactive' }, { quality: 'twoHanded' }, { quality: 'inaccurate' }, { quality: 'blast' }],
    ammo: 'miniNuke',
  },
  {
    name: 'Heavy Incinerator',
    value: 350,
    rarity: 4,
    weight: 10,
    skill: 'bigGuns',
    damage: 5,
    damageType: 'energy',
    fireRate: 3,
    range: 'medium',
    qualities: [{ quality: 'spread' }, { quality: 'burst' }, { quality: 'persistent' }, { quality: 'twoHanded' }, { quality: 'debilitating' }],
    ammo: 'flamerFuel',
  },
  {
    name: 'Junk Jet',
    value: 285,
    rarity: 3,
    weight: 15,
    skill: 'bigGuns',
    damage: 6,
    damageType: 'physical',
    fireRate: 1,
    range: 'medium',
    qualities: [{ quality: 'twoHanded' }],
    ammo: 'none',
  },
  {
    name: 'Flamer',
    value: 137,
    rarity: 3,
    weight: 8.5,
    skill: 'bigGuns',
    damage: 3,
    damageType: 'energy',
    fireRate: 4,
    range: 'close',
    qualities: [{ quality: 'spread' }, { quality: 'burst' }, { quality: 'persistent' }, { quality: 'twoHanded' }, { quality: 'inaccurate' }, { quality: 'debilitating' }],
    ammo: 'flamerFuel',
  },
  {
    name: 'Missile Launcher',
    value: 314,
    rarity: 4,
    weight: 10.5,
    skill: 'bigGuns',
    damage: 11,
    damageType: 'physical',
    fireRate: 0,
    range: 'long',
    qualities: [{ quality: 'twoHanded' }, { quality: 'blast' }],
    ammo: 'missile',
  },
  {
    name: 'Gatling Laser',
    value: 804,
    rarity: 3,
    weight: 9.5,
    skill: 'bigGuns',
    damage: 3,
    damageType: 'energy',
    fireRate: 6,
    range: 'medium',
    qualities: [{ quality: 'burst' }, { quality: 'piercing', value: 1 }, { quality: 'twoHanded' }, { quality: 'gatling' }, { quality: 'inaccurate' }],
    ammo: 'fusionCore',
  },
  {
    name: 'Minigun',
    value: 382,
    rarity: 2,
    weight: 13.5,
    skill: 'bigGuns',
    damage: 3,
    damageType: 'physical',
    fireRate: 5,
    range: 'medium',
    qualities: [{ quality: 'spread' }, { quality: 'burst' }, { quality: 'twoHanded' }, { quality: 'gatling' }, { quality: 'inaccurate' }],
    ammo: '5mm',
  },

  // ===== ARMES DE CORPS À CORPS (Melee Weapons) =====
  {
    name: 'Unarmed Attack',
    value: 0,
    rarity: 0,
    weight: 0,
    skill: 'unarmed',
    damage: 2,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [],
    ammo: 'none',
  },
  {
    name: 'Rock',
    value: 0,
    rarity: 0,
    weight: 0.5,
    skill: 'unarmed',
    damage: 2,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [{ quality: 'vicious' }, { quality: 'thrown' }],
    ammo: 'none',
  },
  {
    name: 'Sword',
    value: 50,
    rarity: 2,
    weight: 1.5,
    skill: 'meleeWeapons',
    damage: 4,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [{ quality: 'piercing', value: 1 }, { quality: 'parry' }],
    ammo: 'none',
  },
  {
    name: 'Combat Knife',
    value: 25,
    rarity: 1,
    weight: 0.5,
    skill: 'meleeWeapons',
    damage: 3,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [{ quality: 'piercing', value: 1 }],
    ammo: 'none',
  },
  {
    name: 'Machete',
    value: 25,
    rarity: 1,
    weight: 1,
    skill: 'meleeWeapons',
    damage: 3,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [{ quality: 'piercing', value: 1 }],
    ammo: 'none',
  },
  {
    name: 'Ripper',
    value: 50,
    rarity: 2,
    weight: 3,
    skill: 'meleeWeapons',
    damage: 4,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [{ quality: 'vicious' }],
    ammo: 'none',
  },
  {
    name: 'Shishkebab',
    value: 200,
    rarity: 3,
    weight: 1.5,
    skill: 'meleeWeapons',
    damage: 5,
    damageType: 'energy',
    fireRate: 0,
    range: 'close',
    qualities: [{ quality: 'piercing', value: 1 }, { quality: 'parry' }],
    ammo: 'none',
  },
  {
    name: 'Switchblade',
    value: 20,
    rarity: 0,
    weight: 0.5,
    skill: 'meleeWeapons',
    damage: 2,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [{ quality: 'piercing', value: 1 }, { quality: 'concealed' }],
    ammo: 'none',
  },
  {
    name: 'Baseball Bat',
    value: 25,
    rarity: 1,
    weight: 1.5,
    skill: 'meleeWeapons',
    damage: 4,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [{ quality: 'twoHanded' }],
    ammo: 'none',
  },
  {
    name: 'Aluminum Baseball Bat',
    value: 32,
    rarity: 2,
    weight: 1,
    skill: 'meleeWeapons',
    damage: 5,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [{ quality: 'twoHanded' }],
    ammo: 'none',
  },
  {
    name: 'Board',
    value: 20,
    rarity: 0,
    weight: 1.5,
    skill: 'meleeWeapons',
    damage: 4,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [{ quality: 'twoHanded' }],
    ammo: 'none',
  },
  {
    name: 'Lead Pipe',
    value: 15,
    rarity: 0,
    weight: 1.5,
    skill: 'meleeWeapons',
    damage: 3,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [],
    ammo: 'none',
  },
  {
    name: 'Pipe Wrench',
    value: 30,
    rarity: 1,
    weight: 1,
    skill: 'meleeWeapons',
    damage: 3,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [],
    ammo: 'none',
  },
  {
    name: 'Pool Cue',
    value: 10,
    rarity: 0,
    weight: 0.5,
    skill: 'meleeWeapons',
    damage: 3,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [{ quality: 'twoHanded' }],
    ammo: 'none',
  },
  {
    name: 'Rolling Pin',
    value: 10,
    rarity: 0,
    weight: 0.5,
    skill: 'meleeWeapons',
    damage: 3,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [],
    ammo: 'none',
  },
  {
    name: 'Baton',
    value: 10,
    rarity: 0,
    weight: 0.5,
    skill: 'meleeWeapons',
    damage: 3,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [],
    ammo: 'none',
  },
  {
    name: 'Sledgehammer',
    value: 40,
    rarity: 2,
    weight: 6,
    skill: 'meleeWeapons',
    damage: 5,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [],
    ammo: 'none',
  },
  {
    name: 'Super Sledge',
    value: 180,
    rarity: 3,
    weight: 10,
    skill: 'meleeWeapons',
    damage: 6,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [{ quality: 'breaking' }, { quality: 'twoHanded' }],
    ammo: 'none',
  },
  {
    name: 'Tire Iron',
    value: 25,
    rarity: 1,
    weight: 1,
    skill: 'meleeWeapons',
    damage: 3,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [],
    ammo: 'none',
  },
  {
    name: 'Walking Cane',
    value: 10,
    rarity: 0,
    weight: 1,
    skill: 'meleeWeapons',
    damage: 3,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [],
    ammo: 'none',
  },

  // ===== MAINS NUES (Unarmed) =====
  {
    name: 'Boxing Glove',
    value: 10,
    rarity: 1,
    weight: 0.5,
    skill: 'unarmed',
    damage: 3,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [{ quality: 'stun' }],
    ammo: 'none',
  },
  {
    name: 'Deathclaw Gauntlet',
    value: 75,
    rarity: 3,
    weight: 5,
    skill: 'unarmed',
    damage: 5,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [{ quality: 'piercing', value: 1 }],
    ammo: 'none',
  },
  {
    name: 'Knuckles',
    value: 10,
    rarity: 1,
    weight: 0.5,
    skill: 'unarmed',
    damage: 3,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [{ quality: 'concealed' }],
    ammo: 'none',
  },
  {
    name: 'Power Fist',
    value: 100,
    rarity: 2,
    weight: 2,
    skill: 'unarmed',
    damage: 4,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [{ quality: 'stun' }],
    ammo: 'none',
  },

  // ===== PROJECTILES (Throwing) =====
  {
    name: 'Throwing Knife',
    value: 10,
    rarity: 1,
    weight: 0.5,
    skill: 'throwing',
    damage: 3,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [{ quality: 'piercing', value: 1 }, { quality: 'concealed' }, { quality: 'thrown' }, { quality: 'silent' }],
    ammo: 'none',
  },
  {
    name: 'Tomahawk',
    value: 15,
    rarity: 2,
    weight: 0.5,
    skill: 'throwing',
    damage: 4,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [{ quality: 'piercing', value: 1 }, { quality: 'thrown' }, { quality: 'silent' }],
    ammo: 'none',
  },
  {
    name: 'Javelin',
    value: 10,
    rarity: 1,
    weight: 2,
    skill: 'throwing',
    damage: 4,
    damageType: 'physical',
    fireRate: 0,
    range: 'medium',
    qualities: [{ quality: 'piercing', value: 1 }, { quality: 'thrown' }, { quality: 'silent' }],
    ammo: 'none',
  },

  // ===== EXPLOSIFS (Explosives) =====
  {
    name: 'Molotov Cocktail',
    value: 20,
    rarity: 1,
    weight: 0.5,
    skill: 'explosives',
    damage: 4,
    damageType: 'energy',
    fireRate: 0,
    range: 'medium',
    qualities: [{ quality: 'persistent' }, { quality: 'thrown' }, { quality: 'blast' }],
    ammo: 'none',
  },
  {
    name: 'Frag Grenade',
    value: 50,
    rarity: 2,
    weight: 0.5,
    skill: 'explosives',
    damage: 6,
    damageType: 'physical',
    fireRate: 0,
    range: 'medium',
    qualities: [{ quality: 'thrown' }, { quality: 'blast' }],
    ammo: 'none',
  },
  {
    name: 'Pulse Grenade',
    value: 100,
    rarity: 3,
    weight: 0.5,
    skill: 'explosives',
    damage: 6,
    damageType: 'energy',
    fireRate: 0,
    range: 'medium',
    qualities: [{ quality: 'stun' }, { quality: 'thrown' }, { quality: 'blast' }],
    ammo: 'none',
  },
  {
    name: 'Plasma Grenade',
    value: 135,
    rarity: 3,
    weight: 0.5,
    skill: 'explosives',
    damage: 9,
    damageType: 'energy',
    fireRate: 0,
    range: 'medium',
    qualities: [{ quality: 'thrown' }, { quality: 'blast' }],
    ammo: 'none',
  },
  {
    name: 'Nuka Grenade',
    value: 100,
    rarity: 4,
    weight: 0.5,
    skill: 'explosives',
    damage: 9,
    damageType: 'energy',
    fireRate: 0,
    range: 'medium',
    qualities: [{ quality: 'vicious' }, { quality: 'breaking' }, { quality: 'radioactive' }, { quality: 'thrown' }, { quality: 'blast' }],
    ammo: 'none',
  },
  {
    name: 'Baseball Grenade',
    value: 40,
    rarity: 1,
    weight: 0.5,
    skill: 'explosives',
    damage: 5,
    damageType: 'physical',
    fireRate: 0,
    range: 'medium',
    qualities: [{ quality: 'thrown' }, { quality: 'blast' }],
    ammo: 'none',
  },

  // ===== MINES (Explosives) =====
  {
    name: 'Bottlecap Mine',
    value: 75,
    rarity: 2,
    weight: 0.5,
    skill: 'explosives',
    damage: 6,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [{ quality: 'mine' }, { quality: 'blast' }],
    ammo: 'none',
  },
  {
    name: 'Frag Mine',
    value: 50,
    rarity: 2,
    weight: 0.5,
    skill: 'explosives',
    damage: 6,
    damageType: 'physical',
    fireRate: 0,
    range: 'close',
    qualities: [{ quality: 'mine' }, { quality: 'blast' }],
    ammo: 'none',
  },
  {
    name: 'Pulse Mine',
    value: 135,
    rarity: 3,
    weight: 0.5,
    skill: 'explosives',
    damage: 9,
    damageType: 'energy',
    fireRate: 0,
    range: 'medium',
    qualities: [{ quality: 'thrown' }, { quality: 'blast' }],
    ammo: 'none',
  },
  {
    name: 'Plasma Mine',
    value: 135,
    rarity: 3,
    weight: 0.5,
    skill: 'explosives',
    damage: 9,
    damageType: 'energy',
    fireRate: 0,
    range: 'medium',
    qualities: [{ quality: 'thrown' }, { quality: 'blast' }],
    ammo: 'none',
  },
  {
    name: 'Nuka Mine',
    value: 100,
    rarity: 4,
    weight: 0.5,
    skill: 'explosives',
    damage: 9,
    damageType: 'energy',
    fireRate: 0,
    range: 'medium',
    qualities: [{ quality: 'vicious' }, { quality: 'breaking' }, { quality: 'radioactive' }, { quality: 'thrown' }, { quality: 'blast' }],
    ammo: 'none',
  },
];

// Helper exports for filtering
export const rangedWeapons = weapons.filter(w =>
  ['smallGuns', 'bigGuns', 'energyWeapons'].includes(w.skill)
);

export const meleeWeapons = weapons.filter(w =>
  ['meleeWeapons', 'unarmed'].includes(w.skill)
);

export const explosives = weapons.filter(w =>
  ['explosives', 'throwing'].includes(w.skill)
);
