/**
 * @file characterStore.js
 * @description Zustand store for normalized character state with localStorage persistence.
 *
 * Architecture overview
 * ─────────────────────
 * State shape (all mutable data lives here):
 *   attributes : { [attrId]: { base, modifiers[], total } }
 *   skills     : { [skillId]: { base, modifiers[], total } }
 *   items      : { [instanceId]: NormalizedItem }
 *   effects    : { [effectId]: NormalizedEffect }
 *
 * Item identity rules
 * ───────────────────
 * Every item requires a *canonical ID* that comes from one of these fields (checked
 * in priority order):
 *   weaponId → id → code → itemId → armorId → clothingId
 *
 * The canonical ID is stored as `item.weaponId` on the normalized item so that
 * WeaponsAndArmorScreen and other consumers can look up catalog data.
 * The *instance key* (the key in the `items` dict) is a UUID-like string generated by
 * `generateItemId(canonicalId, appliedMods)` so that the same weapon with different
 * mods can coexist as separate inventory entries.
 *
 * Kit → Inventory flow
 * ─────────────────────
 * 1. EquipmentKitModal resolves kit items via domain/kitResolver.js
 *    (catalog lookup: weapons/armor/clothing/consumables)
 * 2. toInventoryItems() converts resolved entries to inventory-ready objects
 * 3. CharacterScreen.handleSelectKit() calls addNewItem(item) for each object
 * 4. InventoryScreen reads items via selectItemsByEquipped(state, false)
 *
 * Persistence
 * ───────────
 * The `persist` middleware serializes `attributes`, `skills`, `items`, `effects`
 * to localStorage under the key `character-store`.
 * On load, `normalizeForStore` converts legacy (array-based) saved data to the
 * normalized dict format used here.
 */

import { create } from 'zustand';
import { devtools, persist, createJSONStorage } from 'zustand/middleware';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {
  calculateAttributeTotal,
  calculateSkillTotal,
  normalizeItemParameters,
  calculateDerivedStats,
  calculateParameterTotal
} from './resolvers.js';

import { normalizeForStore, denormalizeForSave, migrateCharacterState } from './migrations.js';
import { CURRENT_SCHEMA_VERSION, LEGACY_SCHEMA_VERSION } from './saveSchema.js';
import { legacyEffectToStore } from './effectsSync.js';
import { createInitialRobotState, createRobotActions } from './robotSlice.js';
import { debugLog } from '../debug/falloutDebug.js';
import perksData from '../../data/perks/perks.json';
import { selectPerkBonuses } from '../../domain/perks.js';
import { applyWeaponWear, repairWeaponDurability } from '../../domain/weaponDurability.js';
// Идентичность предмета (id/стек-ключ = id + моды + имя варианта) — в
// domain/itemIdentity.js: стор, миграции и тесты используют одну логику.
import { generateItemId, generateStackKey } from '../../domain/itemIdentity';
import { catalogGetWeaponModById } from '../../db/catalogSource';
import { getEquipmentCatalog } from '../../i18n/equipmentCatalog';
import { findCatalogEntry, inferItemType } from '../../domain/resolveItem';

// Helper function to generate unique IDs
const generateId = () => `id_${Date.now()}_${Math.random().toString(36).slice(2, 11)}`;

/**
 * Normalize a parameter value to Parameter<T> format
 * @param {*} value - Raw parameter value (number or object)
 * @param {Object} modifier - Optional modifier from mod
 * @returns {Object} Normalized parameter object with {base, modifiers, total}
 */
const normalizeParameter = (value, modifier = null) => {
  if (value === undefined || value === null) return undefined;

  const baseValue = typeof value === 'number' ? value : value?.base ?? 0;

  const parameter = {
    base: baseValue,
    modifiers: [],
    total: baseValue,
  };

  // Apply modifier if present
  if (modifier && modifier.value !== undefined) {
    const modValue = Number(modifier.value) || 0;
    parameter.modifiers.push({
      source: `mod_${modifier.id || 'unknown'}`,
      value: modValue,
      operation: modifier.op || '+',
    });
    // Recalculate total
    parameter.total = calculateParameterTotal(baseValue, parameter.modifiers);
  }

  return parameter;
};

/**
 * Apply mod modifiers to item parameters
 * @param {Object} item - Item with normalized parameters
 * @param {Object} appliedMods - Map of slot -> modId
 * @returns {Object} Item with updated parameters
 */
const applyModModifiers = (item, appliedMods = {}) => {
  if (!item || Object.keys(appliedMods).length === 0) return item;

  const updatedItem = { ...item };

  // For each mod, apply its modifiers to the item parameters
  Object.entries(appliedMods).forEach(([slot, modId]) => {
    const mod = catalogGetWeaponModById(modId);
    if (!mod) return;

    // Apply damage modifier
    if (mod.damageModifier && updatedItem.damage) {
      const modValue = Number(mod.damageModifier.value) || 0;
      updatedItem.damage.modifiers.push({
        source: `mod_${modId}`,
        value: modValue,
        operation: mod.damageModifier.op || '+',
      });
    }

    // Apply fireRate modifier
    if (mod.fireRateModifier && updatedItem.fireRate) {
      const modValue = Number(mod.fireRateModifier.value) || 0;
      updatedItem.fireRate.modifiers.push({
        source: `mod_${modId}`,
        value: modValue,
        operation: mod.fireRateModifier.op || '+',
      });
    }

    // Apply range modifier (if mod has range changes).
    // range is a plain value now; only push a modifier if it is in Parameter shape.
    if (mod.rangeModifier && updatedItem.range && Array.isArray(updatedItem.range.modifiers)) {
      const modValue = Number(mod.rangeModifier.value) || 0;
      updatedItem.range.modifiers.push({
        source: `mod_${modId}`,
        value: modValue,
        operation: mod.rangeModifier.op || '+',
      });
    }

    // Apply damageTypeOverride (if mod changes damage type).
    if (mod.damageTypeOverride) {
      const { op, value } = mod.damageTypeOverride;

      // Получаем текущий damageType (поддержка массива и строки)
      let currentType = updatedItem.damageType;
      if (typeof currentType === 'string') {
        try {
          currentType = JSON.parse(currentType);
        } catch {
          currentType = [currentType];
        }
      }
      if (!Array.isArray(currentType)) {
        currentType = currentType ? [currentType] : ['physical'];
      }

      if (op === 'set') {
        // Замена: полностью перезаписываем массив
        updatedItem.damageType = Array.isArray(value) ? value : [value];
      } else if (op === 'add') {
        // Добавление: добавляем тип, если его нет
        const typesToAdd = Array.isArray(value) ? value : [value];
        for (const t of typesToAdd) {
          if (!currentType.includes(t)) {
            currentType.push(t);
          }
        }
        updatedItem.damageType = currentType;
      }
    }
  });

  return updatedItem;
};

// Helper to get trait, level, and equipment state from context (to be provided by components)
const getCharacterContext = () => {
  // These would come from the CharacterContext or props in real usage
  // For now, return defaults
  return {
    trait: null,
    level: 1,
    equipmentState: {},
  };
};

// Main store creation
const useCharacterStore = create(devtools(
  persist(
    (set, get) => ({
      // --- Initial State ---
      attributes: {},
      skills: {},
      items: {},
      effects: {},
      selectedPerks: [],
      // Per-character journal: tagged skills whose one-time starting reward was issued.
      rewardedSkills: [],
      derivedStats: {}, // Calculated derived stats

      perkBonuses: {},

      // Robot equipment slice (slots / modules / bodyPlan). See robotSlice.js.
      ...createInitialRobotState(),

      // Status flags (not part of persistence)
      isEffectsProcessing: false,

      // --- Actions: Perks ---
      setSelectedPerks: (selectedPerks = []) => {
        set({ selectedPerks });
        get().recalculatePerkBonuses();
        get().recalculateDerivedStats();
      },

      markSkillsAsRewarded: (skills = []) => set((state) => ({
        rewardedSkills: [...new Set([...(state.rewardedSkills || []), ...skills])],
      })),

      recalculatePerkBonuses: () => {
        set({ perkBonuses: selectPerkBonuses(get(), perksData) });
      },

      // --- Actions: Robot equipment (delegated to robotSlice) ---
      ...createRobotActions(set, get),

      // --- Actions: Attributes ---

      /**
       * Update an attribute's base value
       * @param {string} attrId - Attribute ID (e.g., 'STR', 'END')
       * @param {number} delta - Change to apply to base value
       */
      updateAttribute: (attrId, delta) => {
        const state = get();
        const attributes = { ...state.attributes };

        if (!attributes[attrId]) {
          debugLog('store.attrNotFound', { attrId });
          return;
        }

        // Create a copy of the attribute and update base value
        const updatedAttribute = {
          ...attributes[attrId],
          base: (attributes[attrId].base || 0) + delta,
        };

        // Recalculate total
        updatedAttribute.total = calculateAttributeTotal(updatedAttribute);
        attributes[attrId] = updatedAttribute;

        set({ attributes });
        get().recalculateDerivedStats();
      },

      /**
       * Add a modifier to an attribute
       * @param {string} attrId - Attribute ID
       * @param {string} source - Source of the modifier (effect, perk, etc.)
       * @param {number} value - Modifier value
       * @param {string} operation - Operation: '+' (add) or '-' (subtract)
       */
      addAttributeModifier: (attrId, source, value, operation = '+') => {
        const state = get();
        const attributes = { ...state.attributes };

        if (!attributes[attrId]) {
          debugLog('store.attrNotFound', { attrId });
          return;
        }

        // Create a copy of the attribute
        const updatedAttribute = { ...attributes[attrId] };

        // Add the new modifier
        updatedAttribute.modifiers = [
          ...(updatedAttribute.modifiers || []),
          { source, value, operation }
        ];

        // Recalculate total
        updatedAttribute.total = calculateAttributeTotal(updatedAttribute);
        attributes[attrId] = updatedAttribute;

        set({ attributes });
        get().recalculateDerivedStats();
      },

      /**
       * Remove a modifier from an attribute
       * @param {string} attrId - Attribute ID
       * @param {string} source - Source ID to remove
       */
      removeAttributeModifier: (attrId, source) => {
        const state = get();
        const attributes = { ...state.attributes };

        if (!attributes[attrId]) {
          debugLog('store.attrNotFound', { attrId });
          return;
        }

        // Create a copy of the attribute
        const updatedAttribute = { ...attributes[attrId] };

        // Remove modifiers with matching source
        updatedAttribute.modifiers = (updatedAttribute.modifiers || [])
          .filter(mod => mod.source !== source);

        // Recalculate total
        updatedAttribute.total = calculateAttributeTotal(updatedAttribute);
        attributes[attrId] = updatedAttribute;

        set({ attributes });
        get().recalculateDerivedStats();
      },

      // --- Actions: Skills ---

      /**
       * Update a skill's base value
       * @param {string} skillId - Skill ID (e.g., 'SMALL_GUNS', 'MEDICINE')
       * @param {number} delta - Change to apply to base value
       */
      updateSkill: (skillId, delta) => {
        const state = get();
        const skills = { ...state.skills };

        if (!skills[skillId]) {
          debugLog('store.skillNotFound', { skillId });
          return;
        }

        // Create a copy of the skill and update base value
        const updatedSkill = {
          ...skills[skillId],
          base: (skills[skillId].base || 0) + delta,
        };

        // Recalculate total
        updatedSkill.total = calculateSkillTotal(updatedSkill);
        skills[skillId] = updatedSkill;

        set({ skills });
        get().recalculateDerivedStats();
      },

      /**
       * Add a modifier to a skill
       * @param {string} skillId - Skill ID
       * @param {string} source - Source of the modifier (effect, perk, etc.)
       * @param {number} value - Modifier value
       * @param {string} operation - Operation: '+' (add) or '-' (subtract)
       */
      addSkillModifier: (skillId, source, value, operation = '+') => {
        const state = get();
        const skills = { ...state.skills };

        if (!skills[skillId]) {
          debugLog('store.skillNotFound', { skillId });
          return;
        }

        // Create a copy of the skill
        const updatedSkill = { ...skills[skillId] };

        // Add the new modifier
        updatedSkill.modifiers = [
          ...(updatedSkill.modifiers || []),
          { source, value, operation }
        ];

        // Recalculate total
        updatedSkill.total = calculateSkillTotal(updatedSkill);
        skills[skillId] = updatedSkill;

        set({ skills });
        get().recalculateDerivedStats();
      },

      /**
       * Remove a modifier from a skill
       * @param {string} skillId - Skill ID
       * @param {string} source - Source ID to remove
       */
      removeSkillModifier: (skillId, source) => {
        const state = get();
        const skills = { ...state.skills };

        if (!skills[skillId]) {
          debugLog('store.skillNotFound', { skillId });
          return;
        }

        // Create a copy of the skill
        const updatedSkill = { ...skills[skillId] };

        // Remove modifiers with matching source
        updatedSkill.modifiers = (updatedSkill.modifiers || [])
          .filter(mod => mod.source !== source);

        // Recalculate total
        updatedSkill.total = calculateSkillTotal(updatedSkill);
        skills[skillId] = updatedSkill;

        set({ skills });
        get().recalculateDerivedStats();
      },

      // --- Actions: Items ---

      /**
       * Update an item with partial changes
       * @param {string} itemId - Item ID
       * @param {object} patch - Partial item data to merge
       */
      updateItem: (itemId, patch) => {
        const state = get();
        const items = { ...state.items };

        if (!items[itemId]) {
          debugLog('store.itemNotFound', { itemId });
          return;
        }

        debugLog('store.updateItem.before', { itemId, oldItem: items[itemId], patch });
        // Merge the patch with existing item data
        const updatedItem = { ...items[itemId], ...patch };

        // Normalize item parameters (recalculate totals)
        const normalizedItem = normalizeItemParameters(updatedItem);
        debugLog('store.updateItem.after', { itemId, updatedItem, normalizedItem });
        items[itemId] = normalizedItem;

        set({ items });
        get().recalculateDerivedStats();
      },

      /** Spend ammunition and update weapon wear in one state transaction. */
      spendAmmoForWeapon: ({ weaponInstanceId, ammoIds, ammoAmount, durabilityEnabled, baseLossPer10Shots }) => {
        const state = get();
        const weapon = state.items[weaponInstanceId];
        const amount = Math.max(1, Math.floor(Number(ammoAmount) || 1));
        if (!weapon) return { ok: false, reason: 'weapon-not-found' };
        const trackedWeapon = durabilityEnabled && !weapon.durabilityTracked
          ? { ...weapon, durabilityTracked: true, durability: 100, durabilityAmmoRemainder: 0, durabilityWearRemainder: 0 }
          : weapon;
        if (durabilityEnabled && Number(trackedWeapon.durability) <= 0) {
          return { ok: false, reason: 'broken' };
        }

        const acceptedAmmoIds = new Set(ammoIds || []);
        const ammoEntries = Object.entries(state.items).filter(([, item]) =>
          item.itemType === 'ammo' && acceptedAmmoIds.has(item.weaponId || item.id),
        );
        const available = ammoEntries.reduce((sum, [, item]) => sum + (Number(item.quantity) || 1), 0);
        if (available < amount) return { ok: false, reason: 'not-enough-ammo' };

        const items = { ...state.items };
        let remaining = amount;
        for (const [itemId, ammo] of ammoEntries) {
          if (!remaining) break;
          const quantity = Number(ammo.quantity) || 1;
          const spent = Math.min(quantity, remaining);
          if (quantity === spent) delete items[itemId];
          else items[itemId] = { ...ammo, quantity: quantity - spent };
          remaining -= spent;
        }
        if (durabilityEnabled) {
          items[weaponInstanceId] = { ...trackedWeapon, ...applyWeaponWear(trackedWeapon, amount, baseLossPer10Shots) };
        }
        set({ items });
        return { ok: true };
      },

      repairWeapon: (itemId) => {
        const item = get().items[itemId];
        if (!item?.durabilityTracked || Number(item.durability) >= 100) return;
        get().updateItem(itemId, repairWeaponDurability());
      },

      /**
       * Equip an item (set equipped = true)
       * @param {string} itemId - Item ID
       */
      equipItem: (itemId) => {
        const state = get();
        const items = { ...state.items };

        if (!items[itemId]) {
          debugLog('store.itemNotFound', { itemId });
          return;
        }

        // Create a copy of the item and set equipped to true
        const updatedItem = { ...items[itemId], equipped: true };
        items[itemId] = updatedItem;

        set({ items });
        get().recalculateDerivedStats();
      },

      /**
       * Unequip an item (set equipped = false)
       * @param {string} itemId - Item ID
       */
      unequipItem: (itemId) => {
        const state = get();
        const items = { ...state.items };

        if (!items[itemId]) {
          debugLog('store.itemNotFound', { itemId });
          return;
        }

        // Locked items (e.g. robot built-ins delivered by an equipment kit)
        // cannot be unequipped via the normal flow. They are released only
        // when the limb that holds them is swapped — see robotEquip.js.
        if (items[itemId].locked) {
          debugLog('store.lockedUnequipRefused', { itemId });
          return;
        }

        // Create a copy of the item and set equipped to false
        const updatedItem = { ...items[itemId], equipped: false };
        items[itemId] = updatedItem;

        set({ items });
        get().recalculateDerivedStats();
      },

      /**
       * Add a new item to the store (inventory).
       *
       * Accepts any item shape from the kit resolver or the add-item modals.
       * The canonical ID is resolved from the first truthy field in:
       *   item.weaponId → item.id → item.code → item.itemId → item.armorId → item.clothingId
       *
       * Items with no identifier in any of the above fields are silently dropped with a warning.
       *
       * Identical items (same canonicalId + same appliedMods) are stacked rather than
       * duplicated when `quantity` is increased.
       *
       * @param {Object} item - Item data to add
       * @param {string} [item.weaponId]    - Weapon catalog ID (e.g. 'weapon_10mm_pistol')
       * @param {string} [item.id]          - Generic catalog ID (resolved by equipmentCatalog)
       * @param {string} [item.code]        - Legacy code field
       * @param {string} [item.itemId]      - Consumable / misc catalog ID (e.g. 'chem_stimpak')
       * @param {string} [item.armorId]     - Armor catalog ID (e.g. 'armor_leather_chest_001')
       * @param {string} [item.clothingId]  - Clothing catalog ID (e.g. 'clothing_vault_jumpsuit')
       * @param {Object} [item.appliedMods] - Map of slot → modId  { Receiver: 'mod_004' }
       * @param {boolean} [item.equipped=false]
       * @param {number}  [item.quantity=1]
       */
      addNewItem: (item) => {
        const state = get();
        const items = { ...state.items };
        debugLog('items.add.received', {
          name: item?.name,
          itemType: item?.itemType,
          id: item?.id || item?.weaponId || item?.armorId || item?.clothingId || item?.itemId,
        });

        if (!item) {
          debugLog('items.add.invalid', { reason: 'null-or-undefined' });
          return;
        }

        // Get weaponId from item — try all known identifier fields so armor/clothing/misc
        // items that may not have resolved a catalog entry still get stored
        const weaponId = item.weaponId || item.id || item.code
          || item.itemId || item.armorId || item.clothingId;

        if (!weaponId) {
          debugLog('items.add.invalid', { reason: 'no-id-field', item });
          return;
        }
        debugLog('items.add.canonicalId', { weaponId });

        // One simple rule for all entry points (kit, loot, buy, migration):
        // callers may pass only an item id. The store resolves that id against
        // the active JSON catalog once, then stores the UI-ready snapshot plus
        // instance state (quantity, equipped, mods, durability, charges, etc.).
        const catalog = getEquipmentCatalog();
        const requestedType = item.itemType || inferItemType(item);
        // Определяем класс предмета по префиксу id. Это нужно для универсального
        // движка: вызыватель может передать только id — тип подскажет сам id.
        const idUpper = String(weaponId);
        const idPrefixType = idUpper.startsWith('weapon_') ? 'weapon'
          : idUpper.startsWith('ammo_') ? 'ammo'
          : idUpper.startsWith('armor_') ? 'armor'
          : idUpper.startsWith('clothing_') || idUpper.startsWith('headwear_') ? 'clothing'
          : idUpper.startsWith('chem_') ? 'chem'
          : idUpper.startsWith('drink_') ? 'drinks'
          : idUpper.startsWith('food_') ? 'food'
          : idUpper.startsWith('mag_') || idUpper.startsWith('magazine_') ? 'magazine'
          : idUpper.startsWith('robot_') ? 'robotPart'
          : idUpper.startsWith('pa_') || idUpper.startsWith('power_') ? 'powerArmor'
          : null;
        const lookupTypes = [...new Set([
          requestedType,
          idPrefixType,
          'weapon', 'ammo', 'armor', 'clothing', 'chem', 'drinks', 'food', 'magazine',
          'powerArmor', 'robotPart', 'misc',
        ].filter(Boolean))];
        const catalogItem = lookupTypes
          .map((type) => ({ type, entry: findCatalogEntry(catalog, weaponId, type) }))
          .find((result) => result.entry);
        const itemType = item.itemType || catalogItem?.entry?.itemType || catalogItem?.entry?.item_type || catalogItem?.type || requestedType;
        const sourceItem = catalogItem ? { ...catalogItem.entry, ...item, itemType } : { ...item, itemType };

        // Get applied mods
        const appliedMods = sourceItem.appliedMods || {};

        // Generate unique ID for this item instance
        const itemId = sourceItem.uniqueId || generateItemId(
          weaponId,
          appliedMods,
          sourceItem.baseName,
          sourceItem.durabilityTracked ? sourceItem.durability : undefined,
          sourceItem.uniqQualities,
        );

        // Generate stackKey for stacking identical items.
        // Стек = id + прочие параметры (прочность, моды, уникальные качества)
        // + имя: два 100% идентичных предмета — один стек; меч 50 и меч 100
        // прочности — разные; «элегантная» и «дерзкая» форменная одежда
        // (один id, разные uniq-качества) — разные. Предметы со своим ключом
        // (силовая броня, Ядерный Блок — signature по прочности/зарядам/модам)
        // приносят ключ с собой.
        const stackKey = sourceItem.stackKey || generateStackKey(
          weaponId,
          appliedMods,
          sourceItem.baseName,
          sourceItem.durabilityTracked ? sourceItem.durability : undefined,
          sourceItem.uniqQualities,
        );

        // Normalize item data with parameters
        const normalizedItem = {
          id: itemId,
          // instanceId survives display enrichment, whose `id` is the catalog id.
          instanceId: itemId,
          weaponId: weaponId,
          name: sourceItem.name || sourceItem.weaponName || sourceItem.Name || weaponId,
          // baseName — оригинальное имя предмета (без префиксов модов):
          // у вариантов (бритва) отличается от имени истинного предмета,
          // что разделяет стеки и задаёт базу для имён с модами.
          baseName: sourceItem.baseName || undefined,
          // uniqQualities — навешиваемые уникальные качества (id): участвуют
          // в имени предмета и в стек-ключе (см. domain/uniqQuality.js).
          uniqQualities: sourceItem.uniqQualities || undefined,
          itemType,
          equipped: sourceItem.equipped || false,
          // `locked: true` marks items that came from a robot kit. They are
          // equipped at character creation and cannot be removed via the normal
          // unequip flow — only by swapping the limb that holds them.
          locked: Boolean(sourceItem.locked),
          // `requiresMkII` — нерабочее встроенное оружие (ракетница и гранатомёт
          // Секьюритрона до установки ОС Mk II): хранится в инвентаре, но не
          // попадает в список атак, пока механика Mk II не реализована.
          requiresMkII: Boolean(sourceItem.requiresMkII),
          quantity: sourceItem.quantity || 1,
          stackKey: stackKey,
          appliedMods: appliedMods,

          // Normalize numeric parameters (damage, fireRate, etc.)
          damage: normalizeParameter(sourceItem.damage, sourceItem.damageModifier),
          fireRate: normalizeParameter(sourceItem.fireRate, sourceItem.fireRateModifier),
          // range / damageType are descriptive values (e.g. "Medium", "Physical"),
          // NOT numeric stats. Keeping them as plain values avoids (a) corrupting
          // string values into {base:0} and (b) React error #31 when a screen renders
          // the value directly. See docs/architecture/zustand-diagnosis.md (range/damageType fix).
          range: sourceItem.range,
          damageType: sourceItem.damageType,

          // Armor parameters
          physicalDamageRating: normalizeParameter(
            sourceItem.physicalDamageRating,
            sourceItem.physicalDamageRatingModifier
          ),
          energyDamageRating: normalizeParameter(
            sourceItem.energyDamageRating,
            sourceItem.energyDamageRatingModifier
          ),
          radiationDamageRating: normalizeParameter(
            sourceItem.radiationDamageRating,
            sourceItem.radiationDamageRatingModifier
          ),

          // Copy other fields
          code: sourceItem.code,
          cost: sourceItem.cost,
          rarity: sourceItem.rarity,
          weight: sourceItem.weight,
          ammoId: sourceItem.ammoId,
          qualities: sourceItem.qualities,
          imageName: sourceItem.imageName,

          // Optional weapon durability is instance-specific and never catalog data.
          durabilityTracked: Boolean(sourceItem.durabilityTracked),
          durability: sourceItem.durability,
          durabilityAmmoRemainder: sourceItem.durabilityAmmoRemainder,
          durabilityWearRemainder: sourceItem.durabilityWearRemainder,

          // Consumable fields (chems, food, drinks) — preserved verbatim from catalog
          positiveEffect: sourceItem.positiveEffect,
          positiveEffectDuration: sourceItem.positiveEffectDuration,
          positiveEffectLabel: sourceItem.positiveEffectLabel,
          negativeEffect: sourceItem.negativeEffect,
          negativeEffectDuration: sourceItem.negativeEffectDuration,
          negativeEffectLabel: sourceItem.negativeEffectLabel,
          addictionLevel: sourceItem.addictionLevel,

          // Armor / outfit extra fields
          protectedAreas: sourceItem.protectedAreas,
          equippedSlots: sourceItem.equippedSlots,
          equipInstanceId: sourceItem.equipInstanceId,

          // Силовая броня / Ядерный Блок (docs/architecture/power-armor-plan.md §4)
          set: sourceItem.set,
          charges: sourceItem.charges,
          maxCharges: sourceItem.maxCharges,
          hpCurrent: sourceItem.hpCurrent,
          installedPieces: sourceItem.installedPieces,
          installedCore: sourceItem.installedCore,
        };

        // Apply mod modifiers to parameters
        const finalItem = applyModModifiers(normalizedItem, appliedMods);

        const normalizedFinalItem = normalizeItemParameters(finalItem);
        const addedQuantity = Number(normalizedFinalItem.quantity) || 1;
        const existingItemKey = Object.keys(items).find((key) => {
          const existing = items[key];
          return existing
            && (existing.stackKey || existing.id) === (normalizedFinalItem.stackKey || normalizedFinalItem.id)
            && Boolean(existing.equipped) === Boolean(normalizedFinalItem.equipped)
            && Boolean(existing.locked) === Boolean(normalizedFinalItem.locked);
        });

        if (existingItemKey) {
          const existingItem = items[existingItemKey];
          const existingQuantity = Number(existingItem.quantity) || 1;
          items[existingItemKey] = {
            ...existingItem,
            ...normalizedFinalItem,
            id: existingItem.id,
            quantity: existingQuantity + addedQuantity,
          };

          debugLog('items.add.stacked', { key: existingItemKey, quantity: items[existingItemKey].quantity });
          set({ items });
          get().recalculateDerivedStats();

          return existingItemKey;
        }

        // Add item to store
        items[itemId] = normalizedFinalItem;

        debugLog('items.add.stored', { key: itemId, equipped: finalItem.equipped, itemType: finalItem.itemType });
        set({ items });
        get().recalculateDerivedStats();

        return itemId;
      },

      // --- Actions: Effects ---

      /**
       * Add an effect to the store
       * @param {object} effect - Effect data (without id if new)
       */
      addEffect: (effect) => {
        const state = get();
        const effects = { ...state.effects };

        // Generate ID if not provided
        const effectId = effect.id || generateId();

        // Add effect to store with active flag
        effects[effectId] = {
          ...effect,
          id: effectId,
          active: true,
          createdAt: effect.createdAt || Date.now(),
        };

        set({ effects });
        get().triggerDependentCalculations();
      },

      /**
       * Mark an effect as expired (set active = false)
       * @param {string} effectId - Effect ID
       */
      expireEffect: (effectId) => {
        const state = get();
        const effects = { ...state.effects };

        if (!effects[effectId]) {
          debugLog('store.effectNotFound', { effectId });
          return;
        }

        // Mark effect as inactive
        effects[effectId] = {
          ...effects[effectId],
          active: false,
        };

        set({ effects });
        get().triggerDependentCalculations();
      },

      /**
       * Update an existing effect (e.g. scenesLeft after advancing scene)
       */
      updateEffect: (effectId, patch) => {
        const state = get();
        const effects = { ...state.effects };

        if (!effects[effectId]) {
          debugLog('store.effectNotFound', { effectId });
          return;
        }

        effects[effectId] = { ...effects[effectId], ...patch };
        set({ effects });
        get().triggerDependentCalculations();
      },

      /**
       * Remove expired effects from the store
       */
      pruneExpiredEffects: () => {
        const state = get();
        const effects = { ...state.effects };

        // Filter out effects that are not active
        const activeEffects = {};
        Object.entries(effects).forEach(([id, effect]) => {
          if (effect.active) {
            activeEffects[id] = effect;
          }
        });

        if (Object.keys(activeEffects).length !== Object.keys(effects).length) {
          set({ effects: activeEffects });
          get().triggerDependentCalculations();
        }
      },

      /**
       * Recalculate derived stats when effects or equipment change
       */
      triggerDependentCalculations: () => {
        get().recalculateDerivedStats();
      },

      // --- Helper Actions ---

      /**
       * Trigger recalculation of all parameter totals
       */
      recalculateAll: () => {
        const state = get();
        const { attributes, skills, items } = state;

        // Recalculate all attributes
        const updatedAttributes = { ...attributes };
        Object.keys(updatedAttributes).forEach(attrId => {
          const attribute = updatedAttributes[attrId];
          if (attribute) {
            updatedAttributes[attrId] = {
              ...attribute,
              total: calculateAttributeTotal(attribute),
            };
          }
        });

        // Recalculate all skills
        const updatedSkills = { ...skills };
        Object.keys(updatedSkills).forEach(skillId => {
          const skill = updatedSkills[skillId];
          if (skill) {
            updatedSkills[skillId] = {
              ...skill,
              total: calculateSkillTotal(skill),
            };
          }
        });

        // Recalculate all items
        const updatedItems = { ...items };
        Object.keys(updatedItems).forEach(itemId => {
          const item = updatedItems[itemId];
          if (item) {
            updatedItems[itemId] = normalizeItemParameters(item);
          }
        });

        set({
          attributes: updatedAttributes,
          skills: updatedSkills,
          items: updatedItems,
        });

        get().recalculatePerkBonuses();
        get().recalculateDerivedStats();
      },

      /**
       * Recalculate derived stats based on current state
       * This should be called when trait, level, or equipment changes
       * @param {Object} options - Optional: { trait, level, equipmentState }
       */
      recalculateDerivedStats: (options = {}) => {
        const state = get();
        const { attributes, effects, perkBonuses } = state;

        // Merge provided options with the last context pushed via setCharacterContext,
        // falling back to defaults. (Previously this used a stub that always returned
        // trait:null/level:1 — see Fix #4.)
        const context = {
          ...getCharacterContext(),
          ...(state._characterContext || {}),
          ...options,
        };

        // Inject robot equipment so robot carry-weight is computed from the body/armor
        // (the robot slice is the single source of truth — Fix #2).
        const equipmentState = {
          ...(context.equipmentState || {}),
          isRobot: Boolean(context.isRobot ?? context.equipmentState?.isRobot),
          robotSlots: state.robot?.slots || context.equipmentState?.robotSlots || {},
        };

        // Calculate derived stats
        const derivedStats = calculateDerivedStats(
          attributes,
          { ...effects, perkBonuses },
          context.trait,
          context.level,
          { ...equipmentState, perkBonuses }
        );

        set({ derivedStats });
      },

      /**
       * Set character context for derived stats calculation
       * @param {Object} context - { trait, level, equipmentState }
       */
      setCharacterContext: (context) => {
        // Store context for derived stats calculation
        // This would typically be called by CharacterContext
        set({
          _characterContext: {
            trait: context.trait || null,
            level: context.level || 1,
            equipmentState: context.equipmentState || {},
          }
        });
        get().recalculateDerivedStats(context);
      },

      // --- Migration Actions ---

      /**
       * Загрузить данные в store из старого формата (массивов)
       * Используется при начальной загрузке из базы данных
       */
      loadFromLegacyData: (legacyData) => {
        const normalizedState = normalizeForStore(legacyData);
        set({ ...normalizedState, selectedPerks: legacyData?.selectedPerks || [] });
        get().recalculatePerkBonuses();
        get().recalculateAll();
      },

      /**
       * Reset all per-character Zustand data before starting a new character.
       *
       * The store is a working cache for the currently opened character, while
       * characters themselves are saved in the app DB. Seed default attributes
       * and skills immediately so queued React effects from the previously
       * opened character cannot refill an empty store with stale values.
       */
      resetCharacterStore: (legacyDefaults = {}) => {
        const normalizedDefaults = normalizeForStore(legacyDefaults);

        set({
          attributes: normalizedDefaults.attributes || {},
          skills: normalizedDefaults.skills || {},
          items: {},
          effects: {},
          selectedPerks: legacyDefaults?.selectedPerks || [],
          rewardedSkills: legacyDefaults?.rewardedSkills || [],
          perkBonuses: {},
          derivedStats: {},
          _characterContext: undefined,
          ...createInitialRobotState(),
        });

        get().recalculatePerkBonuses();
        get().recalculateAll();
      },

      /**
       * Экспортировать данные в старый формат для сохранения в БД
       */
      exportToLegacyData: () => {
        const state = get();
        return denormalizeForSave(state);
      },

    }),
    {
      name: 'character-store',
      // Storage adapter — works on both React Native (AsyncStorage) and web
      // (react-native-web maps AsyncStorage onto window.localStorage).
      // Без этого на native localStorage отсутствует и персист молча не работает.
      storage: createJSONStorage(() => AsyncStorage),

      // Версия схемы для Zustand persist. При несовпадении сохранённой версии
      // с текущей Zustand вызывает migrate() ДО onRehydrateStorage.
      // Синхронизирована с CURRENT_SCHEMA_VERSION из saveSchema.js — единственным
      // источником истины. При бампе версии: поднять CURRENT_SCHEMA_VERSION
      // и добавить функцию в MIGRATIONS[] в migrations.js.
      version: CURRENT_SCHEMA_VERSION,

      // Прогоняем сохранённое состояние через тот же конвейер миграций,
      // что и SQLite-загрузка (CharacterContext.deserializeState).
      // storedVersion — версия, с которой была записана запись в AsyncStorage.
      migrate: (persistedState, storedVersion) => {
        return migrateCharacterState({
          ...persistedState,
          schemaVersion: Number.isInteger(storedVersion) ? storedVersion : LEGACY_SCHEMA_VERSION,
        });
      },

      partialize: (state) => ({
        attributes: state.attributes,
        skills: state.skills,
        items: state.items,
        effects: state.effects,
        selectedPerks: state.selectedPerks,
        rewardedSkills: state.rewardedSkills,
        robot: state.robot,
        schemaVersion: CURRENT_SCHEMA_VERSION,
      }),
      // On rehydrate, ensure all totals are recalculated
      onRehydrateStorage: () => (state) => {
        if (state) {
          state.recalculateAll();
        }
      },
    }
  ),
  {
    name: 'CharacterStore',
    // Only enable devtools in development
    enabled: process.env.NODE_ENV !== 'production',
  }
));

export default useCharacterStore;
