/**
 * @file characterStore.js
 * @description Zustand store for normalized character state with localStorage persistence.
 *
 * Architecture overview
 * ─────────────────────
 * State shape (all mutable data lives here):
 *   attributes : { [attrId]: { base, modifiers[], total } }
 *   skills     : { [skillId]: { base, modifiers[], total } }
 *   items      : { [instanceId]: NormalizedItem }
 *   effects    : { [effectId]: NormalizedEffect }
 *
 * Item identity rules
 * ───────────────────
 * Every item requires a *canonical ID* that comes from one of these fields (checked
 * in priority order):
 *   weaponId → id → code → itemId → armorId → clothingId
 *
 * The canonical ID is stored as `item.weaponId` on the normalized item so that
 * WeaponsAndArmorScreen and other consumers can look up catalog data.
 * The *instance key* (the key in the `items` dict) is a UUID-like string generated by
 * `generateItemId(canonicalId, appliedMods)` so that the same weapon with different
 * mods can coexist as separate inventory entries.
 *
 * Kit → Inventory flow
 * ─────────────────────
 * 1. EquipmentKitModal resolves kit items via domain/kitResolver.js
 *    (catalog lookup: weapons/armor/clothing/consumables)
 * 2. toInventoryItems() converts resolved entries to inventory-ready objects
 * 3. CharacterScreen.handleSelectKit() calls addNewItem(item) for each object
 * 4. InventoryScreen reads items via selectItemsByEquipped(state, false)
 *
 * Persistence
 * ───────────
 * The `persist` middleware serializes `attributes`, `skills`, `items`, `effects`
 * to localStorage under the key `character-store`.
 * On load, `normalizeForStore` converts legacy (array-based) saved data to the
 * normalized dict format used here.
 */

import { create } from 'zustand';
import { devtools, persist, createJSONStorage } from 'zustand/middleware';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { 
  calculateAttributeTotal, 
  calculateSkillTotal, 
  normalizeItemParameters,
  calculateDerivedStats,
  calculateParameterTotal
} from './resolvers.js';

import { normalizeForStore, denormalizeForSave } from './migrations.js';
import { legacyEffectToStore } from './effectsSync.js';
import { createInitialRobotState, createRobotActions } from './robotSlice.js';

// Helper function to generate unique IDs
const generateId = () => `id_${Date.now()}_${Math.random().toString(36).slice(2, 11)}`;

// Helper to get weapon mod by ID
const getWeaponModById = (modId) => {
  // This will be implemented when weapon mods data is available
  return null;
};

/**
 * Generate unique item ID based on weaponId and applied mods
 * - No mods: weaponId (e.g., 'weapon_10mm_pistol')
 * - With mods: weaponId_mods_mod1_mod2 (e.g., 'weapon_10mm_pistol_mods_mod_004_mod_017')
 */
const generateItemId = (weaponId, appliedMods = {}) => {
  if (!weaponId) return generateId();
  
  const modIds = Object.entries(appliedMods)
    .sort(([k1], [k2]) => k1.localeCompare(k2))
    .map(([slot, modId]) => modId)
    .join('_');
  
  return modIds ? `${weaponId}_mods_${modIds}` : weaponId;
};

/**
 * Generate stackKey for stacking identical items
 * - No mods: weaponId
 * - With mods: weaponId_mods_mod1_mod2
 */
const generateStackKey = (weaponId, appliedMods = {}) => {
  if (!weaponId) return generateId();
  
  const modIds = Object.entries(appliedMods)
    .sort(([k1], [k2]) => k1.localeCompare(k2))
    .map(([slot, modId]) => modId)
    .join('_');
  
  return modIds ? `${weaponId}_mods_${modIds}` : weaponId;
};

/**
 * Normalize a parameter value to Parameter<T> format
 * @param {*} value - Raw parameter value (number or object)
 * @param {Object} modifier - Optional modifier from mod
 * @returns {Object} Normalized parameter object with {base, modifiers, total}
 */
const normalizeParameter = (value, modifier = null) => {
  if (value === undefined || value === null) return undefined;
  
  const baseValue = typeof value === 'number' ? value : value?.base ?? 0;
  
  const parameter = {
    base: baseValue,
    modifiers: [],
    total: baseValue,
  };
  
  // Apply modifier if present
  if (modifier && modifier.value !== undefined) {
    const modValue = Number(modifier.value) || 0;
    parameter.modifiers.push({
      source: `mod_${modifier.id || 'unknown'}`,
      value: modValue,
      operation: modifier.op || '+',
    });
    // Recalculate total
    parameter.total = calculateParameterTotal(baseValue, parameter.modifiers);
  }
  
  return parameter;
};

/**
 * Apply mod modifiers to item parameters
 * @param {Object} item - Item with normalized parameters
 * @param {Object} appliedMods - Map of slot -> modId
 * @returns {Object} Item with updated parameters
 */
const applyModModifiers = (item, appliedMods = {}) => {
  if (!item || Object.keys(appliedMods).length === 0) return item;
  
  const updatedItem = { ...item };
  
  // For each mod, apply its modifiers to the item parameters
  Object.entries(appliedMods).forEach(([slot, modId]) => {
    const mod = getWeaponModById(modId);
    if (!mod) return;
    
    // Apply damage modifier
    if (mod.damageModifier && updatedItem.damage) {
      const modValue = Number(mod.damageModifier.value) || 0;
      updatedItem.damage.modifiers.push({
        source: `mod_${modId}`,
        value: modValue,
        operation: mod.damageModifier.op || '+',
      });
    }
    
    // Apply fireRate modifier
    if (mod.fireRateModifier && updatedItem.fireRate) {
      const modValue = Number(mod.fireRateModifier.value) || 0;
      updatedItem.fireRate.modifiers.push({
        source: `mod_${modId}`,
        value: modValue,
        operation: mod.fireRateModifier.op || '+',
      });
    }
    
    // Apply range modifier (if mod has range changes).
    // range is a plain value now; only push a modifier if it is in Parameter shape.
    if (mod.rangeModifier && updatedItem.range && Array.isArray(updatedItem.range.modifiers)) {
      const modValue = Number(mod.rangeModifier.value) || 0;
      updatedItem.range.modifiers.push({
        source: `mod_${modId}`,
        value: modValue,
        operation: mod.rangeModifier.op || '+',
      });
    }

    // Apply damageType modifier (if mod changes damage type). damageType is a plain
    // string; just overwrite it.
    if (mod.damageType) {
      updatedItem.damageType = mod.damageType;
    }
  });
  
  return updatedItem;
};

// Helper to get trait, level, and equipment state from context (to be provided by components)
const getCharacterContext = () => {
  // These would come from the CharacterContext or props in real usage
  // For now, return defaults
  return {
    trait: null,
    level: 1,
    equipmentState: {},
  };
};

// Main store creation
const useCharacterStore = create(devtools(
  persist(
    (set, get) => ({
      // --- Initial State ---
      attributes: {},
      skills: {},
      items: {},
      effects: {},
      derivedStats: {}, // Calculated derived stats

      // Robot equipment slice (slots / modules / bodyPlan). See robotSlice.js.
      ...createInitialRobotState(),

      // Status flags (not part of persistence)
      isEffectsProcessing: false,

      // --- Actions: Robot equipment (delegated to robotSlice) ---
      ...createRobotActions(set, get),
      
      // --- Actions: Attributes ---
      
      /**
       * Update an attribute's base value
       * @param {string} attrId - Attribute ID (e.g., 'STR', 'END')
       * @param {number} delta - Change to apply to base value
       */
      updateAttribute: (attrId, delta) => {
        const state = get();
        const attributes = { ...state.attributes };
        
        if (!attributes[attrId]) {
          console.warn(`Attribute ${attrId} not found`);
          return;
        }
        
        // Create a copy of the attribute and update base value
        const updatedAttribute = {
          ...attributes[attrId],
          base: (attributes[attrId].base || 0) + delta,
        };
        
        // Recalculate total
        updatedAttribute.total = calculateAttributeTotal(updatedAttribute);
        attributes[attrId] = updatedAttribute;
        
        set({ attributes });
        get().recalculateDerivedStats();
      },
      
      /**
       * Add a modifier to an attribute
       * @param {string} attrId - Attribute ID
       * @param {string} source - Source of the modifier (effect, perk, etc.)
       * @param {number} value - Modifier value
       * @param {string} operation - Operation: '+' (add) or '-' (subtract)
       */
      addAttributeModifier: (attrId, source, value, operation = '+') => {
        const state = get();
        const attributes = { ...state.attributes };
        
        if (!attributes[attrId]) {
          console.warn(`Attribute ${attrId} not found`);
          return;
        }
        
        // Create a copy of the attribute
        const updatedAttribute = { ...attributes[attrId] };
        
        // Add the new modifier
        updatedAttribute.modifiers = [
          ...(updatedAttribute.modifiers || []),
          { source, value, operation }
        ];
        
        // Recalculate total
        updatedAttribute.total = calculateAttributeTotal(updatedAttribute);
        attributes[attrId] = updatedAttribute;
        
        set({ attributes });
        get().recalculateDerivedStats();
      },
      
      /**
       * Remove a modifier from an attribute
       * @param {string} attrId - Attribute ID
       * @param {string} source - Source ID to remove
       */
      removeAttributeModifier: (attrId, source) => {
        const state = get();
        const attributes = { ...state.attributes };
        
        if (!attributes[attrId]) {
          console.warn(`Attribute ${attrId} not found`);
          return;
        }
        
        // Create a copy of the attribute
        const updatedAttribute = { ...attributes[attrId] };
        
        // Remove modifiers with matching source
        updatedAttribute.modifiers = (updatedAttribute.modifiers || [])
          .filter(mod => mod.source !== source);
        
        // Recalculate total
        updatedAttribute.total = calculateAttributeTotal(updatedAttribute);
        attributes[attrId] = updatedAttribute;
        
        set({ attributes });
        get().recalculateDerivedStats();
      },
      
      // --- Actions: Skills ---
      
      /**
       * Update a skill's base value
       * @param {string} skillId - Skill ID (e.g., 'SMALL_GUNS', 'MEDICINE')
       * @param {number} delta - Change to apply to base value
       */
      updateSkill: (skillId, delta) => {
        const state = get();
        const skills = { ...state.skills };
        
        if (!skills[skillId]) {
          console.warn(`Skill ${skillId} not found`);
          return;
        }
        
        // Create a copy of the skill and update base value
        const updatedSkill = {
          ...skills[skillId],
          base: (skills[skillId].base || 0) + delta,
        };
        
        // Recalculate total
        updatedSkill.total = calculateSkillTotal(updatedSkill);
        skills[skillId] = updatedSkill;
        
        set({ skills });
        get().recalculateDerivedStats();
      },
      
      /**
       * Add a modifier to a skill
       * @param {string} skillId - Skill ID
       * @param {string} source - Source of the modifier (effect, perk, etc.)
       * @param {number} value - Modifier value
       * @param {string} operation - Operation: '+' (add) or '-' (subtract)
       */
      addSkillModifier: (skillId, source, value, operation = '+') => {
        const state = get();
        const skills = { ...state.skills };
        
        if (!skills[skillId]) {
          console.warn(`Skill ${skillId} not found`);
          return;
        }
        
        // Create a copy of the skill
        const updatedSkill = { ...skills[skillId] };
        
        // Add the new modifier
        updatedSkill.modifiers = [
          ...(updatedSkill.modifiers || []),
          { source, value, operation }
        ];
        
        // Recalculate total
        updatedSkill.total = calculateSkillTotal(updatedSkill);
        skills[skillId] = updatedSkill;
        
        set({ skills });
        get().recalculateDerivedStats();
      },
      
      /**
       * Remove a modifier from a skill
       * @param {string} skillId - Skill ID
       * @param {string} source - Source ID to remove
       */
      removeSkillModifier: (skillId, source) => {
        const state = get();
        const skills = { ...state.skills };
        
        if (!skills[skillId]) {
          console.warn(`Skill ${skillId} not found`);
          return;
        }
        
        // Create a copy of the skill
        const updatedSkill = { ...skills[skillId] };
        
        // Remove modifiers with matching source
        updatedSkill.modifiers = (updatedSkill.modifiers || [])
          .filter(mod => mod.source !== source);
        
        // Recalculate total
        updatedSkill.total = calculateSkillTotal(updatedSkill);
        skills[skillId] = updatedSkill;
        
        set({ skills });
        get().recalculateDerivedStats();
      },
      
      // --- Actions: Items ---
      
      /**
       * Update an item with partial changes
       * @param {string} itemId - Item ID
       * @param {object} patch - Partial item data to merge
       */
      updateItem: (itemId, patch) => {
        const state = get();
        const items = { ...state.items };
        
        if (!items[itemId]) {
          console.warn(`Item ${itemId} not found`);
          return;
        }
        
        // Merge the patch with existing item data
        const updatedItem = { ...items[itemId], ...patch };
        
        // Normalize item parameters (recalculate totals)
        const normalizedItem = normalizeItemParameters(updatedItem);
        items[itemId] = normalizedItem;
        
        set({ items });
        get().recalculateDerivedStats();
      },
      
      /**
       * Equip an item (set equipped = true)
       * @param {string} itemId - Item ID
       */
      equipItem: (itemId) => {
        const state = get();
        const items = { ...state.items };
        
        if (!items[itemId]) {
          console.warn(`Item ${itemId} not found`);
          return;
        }
        
        // Create a copy of the item and set equipped to true
        const updatedItem = { ...items[itemId], equipped: true };
        items[itemId] = updatedItem;
        
        set({ items });
        get().recalculateDerivedStats();
      },
      
      /**
       * Unequip an item (set equipped = false)
       * @param {string} itemId - Item ID
       */
      unequipItem: (itemId) => {
        const state = get();
        const items = { ...state.items };

        if (!items[itemId]) {
          console.warn(`Item ${itemId} not found`);
          return;
        }

        // Locked items (e.g. robot built-ins delivered by an equipment kit)
        // cannot be unequipped via the normal flow. They are released only
        // when the limb that holds them is swapped — see robotEquip.js.
        if (items[itemId].locked) {
          console.warn(`Item ${itemId} is locked (robot built-in); refuse to unequip.`);
          return;
        }

        // Create a copy of the item and set equipped to false
        const updatedItem = { ...items[itemId], equipped: false };
        items[itemId] = updatedItem;

        set({ items });
        get().recalculateDerivedStats();
      },
      
      /**
       * Add a new item to the store (inventory).
       *
       * Accepts any item shape from the kit resolver or the add-item modals.
       * The canonical ID is resolved from the first truthy field in:
       *   item.weaponId → item.id → item.code → item.itemId → item.armorId → item.clothingId
       *
       * Items with no identifier in any of the above fields are silently dropped with a warning.
       *
       * Identical items (same canonicalId + same appliedMods) are stacked rather than
       * duplicated when `quantity` is increased.
       *
       * @param {Object} item - Item data to add
       * @param {string} [item.weaponId]    - Weapon catalog ID (e.g. 'weapon_10mm_pistol')
       * @param {string} [item.id]          - Generic catalog ID (resolved by equipmentCatalog)
       * @param {string} [item.code]        - Legacy code field
       * @param {string} [item.itemId]      - Consumable / misc catalog ID (e.g. 'chem_stimpak')
       * @param {string} [item.armorId]     - Armor catalog ID (e.g. 'armor_leather_chest_001')
       * @param {string} [item.clothingId]  - Clothing catalog ID (e.g. 'clothing_vault_jumpsuit')
       * @param {Object} [item.appliedMods] - Map of slot → modId  { Receiver: 'mod_004' }
       * @param {boolean} [item.equipped=false]
       * @param {number}  [item.quantity=1]
       */
      addNewItem: (item) => {
        const state = get();
        const items = { ...state.items };
        
        if (!item) {
          console.warn('addNewItem: item is null or undefined');
          return;
        }
        
        // Get weaponId from item — try all known identifier fields so armor/clothing/misc
        // items that may not have resolved a catalog entry still get stored
        const weaponId = item.weaponId || item.id || item.code
          || item.itemId || item.armorId || item.clothingId;
        
        if (!weaponId) {
          console.warn('addNewItem: item missing any known id field', item);
          return;
        }
        
        // Get applied mods
        const appliedMods = item.appliedMods || {};
        
        // Generate unique ID for this item instance
        const itemId = item.uniqueId || generateItemId(weaponId, appliedMods);
        
        // Generate stackKey for stacking identical items
        const stackKey = generateStackKey(weaponId, appliedMods);
        
        // Normalize item data with parameters
        const normalizedItem = {
          id: itemId,
          weaponId: weaponId,
          name: item.name || item.weaponName || item.Name || weaponId,
          itemType: item.itemType || 'weapon',
          equipped: item.equipped || false,
          // `locked: true` marks items that came from a robot kit. They are
          // equipped at character creation and cannot be removed via the normal
          // unequip flow — only by swapping the limb that holds them.
          locked: Boolean(item.locked),
          quantity: item.quantity || 1,
          stackKey: stackKey,
          appliedMods: appliedMods,
          
          // Normalize numeric parameters (damage, fireRate, etc.)
          damage: normalizeParameter(item.damage, item.damageModifier),
          fireRate: normalizeParameter(item.fireRate, item.fireRateModifier),
          // range / damageType are descriptive values (e.g. "Medium", "Physical"),
          // NOT numeric stats. Keeping them as plain values avoids (a) corrupting
          // string values into {base:0} and (b) React error #31 when a screen renders
          // the value directly. See docs/architecture/zustand-diagnosis.md (range/damageType fix).
          range: item.range,
          damageType: item.damageType,
          
          // Armor parameters
          physicalDamageRating: normalizeParameter(
            item.physicalDamageRating, 
            item.physicalDamageRatingModifier
          ),
          energyDamageRating: normalizeParameter(
            item.energyDamageRating, 
            item.energyDamageRatingModifier
          ),
          radiationDamageRating: normalizeParameter(
            item.radiationDamageRating, 
            item.radiationDamageRatingModifier
          ),
          
          // Copy other fields
          code: item.code,
          cost: item.cost,
          rarity: item.rarity,
          weight: item.weight,
          ammoId: item.ammoId,
          qualities: item.qualities,
          imageName: item.imageName,

          // Consumable fields (chems, food, drinks) — preserved verbatim from catalog
          positiveEffect: item.positiveEffect,
          positiveEffectDuration: item.positiveEffectDuration,
          positiveEffectLabel: item.positiveEffectLabel,
          negativeEffect: item.negativeEffect,
          negativeEffectDuration: item.negativeEffectDuration,
          negativeEffectLabel: item.negativeEffectLabel,
          addictionLevel: item.addictionLevel,

          // Armor / outfit extra fields
          protectedAreas: item.protectedAreas,
          equippedSlots: item.equippedSlots,
          equipInstanceId: item.equipInstanceId,
        };
        
        // Apply mod modifiers to parameters
        const finalItem = applyModModifiers(normalizedItem, appliedMods);
        
        // Add item to store
        items[itemId] = normalizeItemParameters(finalItem);
        
        set({ items });
        get().recalculateDerivedStats();
        
        return itemId;
      },
      
      // --- Actions: Effects ---
      
      /**
       * Add an effect to the store
       * @param {object} effect - Effect data (without id if new)
       */
      addEffect: (effect) => {
        const state = get();
        const effects = { ...state.effects };
        
        // Generate ID if not provided
        const effectId = effect.id || generateId();
        
        // Add effect to store with active flag
        effects[effectId] = {
          ...effect,
          id: effectId,
          active: true,
          createdAt: effect.createdAt || Date.now(),
        };
        
        set({ effects });
        get().triggerDependentCalculations();
      },
      
      /**
       * Mark an effect as expired (set active = false)
       * @param {string} effectId - Effect ID
       */
      expireEffect: (effectId) => {
        const state = get();
        const effects = { ...state.effects };
        
        if (!effects[effectId]) {
          console.warn(`Effect ${effectId} not found`);
          return;
        }
        
        // Mark effect as inactive
        effects[effectId] = {
          ...effects[effectId],
          active: false,
        };
        
        set({ effects });
        get().triggerDependentCalculations();
      },

      /**
       * Update an existing effect (e.g. scenesLeft after advancing scene)
       */
      updateEffect: (effectId, patch) => {
        const state = get();
        const effects = { ...state.effects };

        if (!effects[effectId]) {
          console.warn(`Effect ${effectId} not found`);
          return;
        }

        effects[effectId] = { ...effects[effectId], ...patch };
        set({ effects });
        get().triggerDependentCalculations();
      },
      
      /**
       * Remove expired effects from the store
       */
      pruneExpiredEffects: () => {
        const state = get();
        const effects = { ...state.effects };
        
        // Filter out effects that are not active
        const activeEffects = {};
        Object.entries(effects).forEach(([id, effect]) => {
          if (effect.active) {
            activeEffects[id] = effect;
          }
        });
        
        if (Object.keys(activeEffects).length !== Object.keys(effects).length) {
          set({ effects: activeEffects });
          get().triggerDependentCalculations();
        }
      },

      /**
       * Recalculate derived stats when effects or equipment change
       */
      triggerDependentCalculations: () => {
        get().recalculateDerivedStats();
      },
      
      // --- Helper Actions ---
      
      /**
       * Trigger recalculation of all parameter totals
       */
      recalculateAll: () => {
        const state = get();
        const { attributes, skills, items } = state;
        
        // Recalculate all attributes
        const updatedAttributes = { ...attributes };
        Object.keys(updatedAttributes).forEach(attrId => {
          const attribute = updatedAttributes[attrId];
          if (attribute) {
            updatedAttributes[attrId] = {
              ...attribute,
              total: calculateAttributeTotal(attribute),
            };
          }
        });
        
        // Recalculate all skills
        const updatedSkills = { ...skills };
        Object.keys(updatedSkills).forEach(skillId => {
          const skill = updatedSkills[skillId];
          if (skill) {
            updatedSkills[skillId] = {
              ...skill,
              total: calculateSkillTotal(skill),
            };
          }
        });
        
        // Recalculate all items
        const updatedItems = { ...items };
        Object.keys(updatedItems).forEach(itemId => {
          const item = updatedItems[itemId];
          if (item) {
            updatedItems[itemId] = normalizeItemParameters(item);
          }
        });
        
        set({
          attributes: updatedAttributes,
          skills: updatedSkills,
          items: updatedItems,
        });
        
        get().recalculateDerivedStats();
      },
      
      /**
       * Recalculate derived stats based on current state
       * This should be called when trait, level, or equipment changes
       * @param {Object} options - Optional: { trait, level, equipmentState }
       */
      recalculateDerivedStats: (options = {}) => {
        const state = get();
        const { attributes, effects } = state;

        // Merge provided options with the last context pushed via setCharacterContext,
        // falling back to defaults. (Previously this used a stub that always returned
        // trait:null/level:1 — see Fix #4.)
        const context = {
          ...getCharacterContext(),
          ...(state._characterContext || {}),
          ...options,
        };

        // Inject robot equipment so robot carry-weight is computed from the body/armor
        // (the robot slice is the single source of truth — Fix #2).
        const equipmentState = {
          ...(context.equipmentState || {}),
          isRobot: Boolean(context.isRobot ?? context.equipmentState?.isRobot),
          robotSlots: state.robot?.slots || context.equipmentState?.robotSlots || {},
        };

        // Calculate derived stats
        const derivedStats = calculateDerivedStats(
          attributes,
          effects,
          context.trait,
          context.level,
          equipmentState
        );

        set({ derivedStats });
      },
      
      /**
       * Set character context for derived stats calculation
       * @param {Object} context - { trait, level, equipmentState }
       */
      setCharacterContext: (context) => {
        // Store context for derived stats calculation
        // This would typically be called by CharacterContext
        set({ 
          _characterContext: {
            trait: context.trait || null,
            level: context.level || 1,
            equipmentState: context.equipmentState || {},
          }
        });
        get().recalculateDerivedStats(context);
      },
      
      // --- Migration Actions ---
      
      /**
       * Загрузить данные в store из старого формата (массивов)
       * Используется при начальной загрузке из базы данных
       */
      loadFromLegacyData: (legacyData) => {
        const normalizedState = normalizeForStore(legacyData);
        set(normalizedState);
        get().recalculateAll();
      },
      
      /**
       * Экспортировать данные в старый формат для сохранения в БД
       */
      exportToLegacyData: () => {
        const state = get();
        return denormalizeForSave(state);
      },
      
    }),
    {
      name: 'character-store',
      // Storage adapter — works on both React Native (AsyncStorage) and web
      // (react-native-web maps AsyncStorage onto window.localStorage).
      // Без этого на native localStorage отсутствует и персист молча не работает.
      storage: createJSONStorage(() => AsyncStorage),
      partialize: (state) => ({
        attributes: state.attributes,
        skills: state.skills,
        items: state.items,
        effects: state.effects,
        robot: state.robot,
        schemaVersion: 1,
      }),
      // On rehydrate, ensure all totals are recalculated
      onRehydrateStorage: () => (state) => {
        if (state) {
          state.recalculateAll();
        }
      },
    }
  ),
  {
    name: 'CharacterStore',
    // Only enable devtools in development
    enabled: process.env.NODE_ENV !== 'production',
  }
));

export default useCharacterStore;