import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: 10,
    width: '90%',
    maxHeight: '85%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  modalTitle: { fontSize: 18, fontWeight: 'bold' },
  closeButton: { padding: 5 },
  closeButtonText: { fontSize: 20, color: '#666' },
  modalBody: { padding: 15 },
  itemInfo: {
    marginBottom: 16,
    padding: 10,
    backgroundColor: '#f5f5f5',
    borderRadius: 5,
  },
  itemTitle: { fontSize: 16, fontWeight: 'bold', marginBottom: 4 },
  itemStats: { fontSize: 14, color: '#666' },
  modificationsSection: { marginBottom: 16 },
  sectionTitle: { fontSize: 15, fontWeight: 'bold', marginBottom: 8 },
  collapsibleSection: {
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 6,
    overflow: 'hidden',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#f0f0f0',
  },
  sectionHeaderTitle: { fontSize: 14, fontWeight: '600' },
  expandIcon: { fontSize: 14, color: '#666' },
  sectionContent: { padding: 8 },
  modificationItem: {
    padding: 10,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 5,
    marginBottom: 6,
    backgroundColor: '#fff',
  },
  selectedModification: { borderColor: '#007AFF', backgroundColor: '#E3F2FD' },
  modificationName: { fontSize: 14, fontWeight: 'bold', marginBottom: 4 },
  modificationText: { fontSize: 12, color: '#666', marginBottom: 2 },
  previewSection: { marginBottom: 8 },
  previewContent: {
    padding: 10,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 5,
    backgroundColor: '#f9f9f9',
  },
  previewTitle: { fontSize: 15, fontWeight: 'bold', marginBottom: 6 },
  previewStats: { fontSize: 13, color: '#444', marginBottom: 2 },
  previewText: { fontSize: 12, color: '#666', marginTop: 4 },
  modalFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 15,
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  cancelButton: {
    flex: 1,
    padding: 10,
    marginRight: 8,
    borderRadius: 5,
    backgroundColor: '#f0f0f0',
    alignItems: 'center',
  },
  cancelButtonText: { color: '#666', fontWeight: '600' },
  applyButton: {
    flex: 1,
    padding: 10,
    marginLeft: 8,
    borderRadius: 5,
    backgroundColor: '#007AFF',
    alignItems: 'center',
  },
  applyButtonText: { color: 'white', fontWeight: '600' },
});

export default styles;
