import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: 'transparent' },
  titleContainer: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: 'rgba(0,0,0,0.75)',
    borderBottomWidth: 1,
    borderBottomColor: '#d4af37',
  },
  title: {
    color: '#f0e68c',
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    letterSpacing: 1,
  },
  subtitle: { color: '#ccc', fontSize: 13, textAlign: 'center', marginTop: 2 },
  languageRow: {
    paddingTop: 8,
    paddingHorizontal: 16,
    paddingBottom: 6,
    backgroundColor: 'rgba(0,0,0,0.75)',
    borderBottomWidth: 1,
    borderBottomColor: '#d4af37',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  menuCell: { width: 44, marginRight: 8 },
  menuButton: {
    width: 38,
    height: 38,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#6b7280',
    backgroundColor: 'rgba(17,24,39,0.85)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  languageContainer: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#6b7280',
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: 'rgba(17,24,39,0.85)',
  },
  langSegment: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    minHeight: 34,
    borderRightWidth: 1,
    borderRightColor: '#6b7280',
    justifyContent: 'center',
    alignItems: 'center',
  },
  langSegmentText: { color: '#9ca3af', fontSize: 13, textTransform: 'uppercase' },
  langSegmentLeft: { borderTopLeftRadius: 8, borderBottomLeftRadius: 8 },
  langSegmentRight: {
    borderRightWidth: 0,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
  },
  langSegmentActive: { backgroundColor: 'white' },
  langSegmentTextActive: { color: '#111827', fontWeight: '700' },
  scrollView: { flex: 1 },
  scrollContent: { padding: 12, paddingBottom: 24 },
  loader: { marginTop: 60 },
  row: { flexDirection: 'row', marginBottom: 10 },
  createCell: {
    flex: 1,
    margin: 5,
    aspectRatio: 0.75,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#5a5a5a',
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.85)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  createPlus: { fontSize: 48, color: '#5a5a5a', lineHeight: 56, fontWeight: '200' },
  createLabel: {
    fontSize: 12,
    color: '#5a5a5a',
    textAlign: 'center',
    marginTop: 4,
    lineHeight: 16,
  },
  characterCell: {
    flex: 1,
    margin: 5,
    aspectRatio: 0.75,
    borderWidth: 1,
    borderColor: '#5a5a5a',
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.92)',
    overflow: 'hidden',
  },
  characterImageContainer: { flex: 1, backgroundColor: '#e0e0e0' },
  deleteButton: {
    position: 'absolute',
    top: 5,
    right: 5,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.25,
    shadowRadius: 2,
  },
  deleteIcon: { fontSize: 15, lineHeight: 18 },
  characterActionButton: {
    position: 'absolute',
    right: 5,
    bottom: 5,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.25,
    shadowRadius: 2,
  },
  characterActionBackdrop: { flex: 1, backgroundColor: 'transparent' },
  characterActionMenu: {
    position: 'absolute',
    width: 220,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#9ca3af',
    backgroundColor: '#fff',
    elevation: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.28,
    shadowRadius: 8,
  },
  characterActionItem: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  characterActionText: { flex: 1, color: '#111827', fontSize: 14 },
  characterActionDeleteText: { color: '#b91c1c' },
  characterImage: { width: '100%', height: '100%' },
  characterImagePlaceholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#c8c8c8',
  },
  characterImagePlaceholderText: { fontSize: 36, color: '#888' },
  characterName: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#222',
    textAlign: 'center',
    paddingHorizontal: 4,
    paddingTop: 4,
    paddingBottom: 2,
  },
  characterLevel: { fontSize: 10, color: '#555', textAlign: 'center', paddingBottom: 4 },
  emptyCell: { flex: 1, margin: 5, aspectRatio: 0.75 },
  disabledCell: { opacity: 0.45 },
  dragHandle: { position: 'absolute', top: 5, left: 5, zIndex: 20, width: 28, height: 28, borderRadius: 14, backgroundColor: 'white', alignItems: 'center', justifyContent: 'center' },
  folderCell: { flex: 1, margin: 5, aspectRatio: 0.75, borderWidth: 1, borderColor: '#d4af37', borderRadius: 8, backgroundColor: '#111827', justifyContent: 'center', alignItems: 'center', padding: 8 },
  folderDropTarget: { borderWidth: 3, backgroundColor: '#374151' },
  folderName: { color: '#f0e68c', textAlign: 'center', fontWeight: '700', marginTop: 8 },
  folderCount: { color: '#d1d5db', fontSize: 11, marginTop: 4 },
  folderDeleteButton: { position: 'absolute', top: 5, right: 5, width: 24, height: 24, borderRadius: 12, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center', zIndex: 2 },
  folderDraftCell: { flex: 1, margin: 5, aspectRatio: 0.75, borderWidth: 1, borderStyle: 'dashed', borderColor: '#d4af37', borderRadius: 8, backgroundColor: 'rgba(255,255,255,0.92)', justifyContent: 'center', alignItems: 'center', padding: 8 },
  folderNameInput: { width: '100%', borderBottomWidth: 1, borderColor: '#555', textAlign: 'center', marginTop: 8, padding: 4 },
  folderDraftActions: { flexDirection: 'row', gap: 12, marginTop: 12 },
  folderHeader: { marginHorizontal: 16, marginBottom: 8, padding: 10, borderWidth: 1, borderColor: '#d4af37', borderRadius: 8, backgroundColor: '#111827' },
  folderBack: { color: '#93c5fd', fontWeight: '700' },
  folderHeaderTitle: { color: '#f0e68c', fontSize: 18, fontWeight: '700', marginTop: 6 },
  folderHeaderCount: { color: '#d1d5db', marginTop: 2 },
  rootDropZone: { marginTop: 10, padding: 10, borderWidth: 1, borderStyle: 'dashed', borderColor: '#d4af37', borderRadius: 6 },
  rootDropText: { color: '#f0e68c', textAlign: 'center' },
  moveHint: { color: '#f0e68c', textAlign: 'center', marginHorizontal: 16, marginBottom: 8 },
  dragPreview: { position: 'absolute', zIndex: 100, width: 108, padding: 8, borderRadius: 8, backgroundColor: '#111827', borderWidth: 2, borderColor: '#d4af37', opacity: 1 },
  dragPreviewText: { color: '#f0e68c', textAlign: 'center', fontWeight: '700' },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    paddingTop: 58,
    paddingLeft: 16,
  },
  menuPanel: {
    width: 280,
    backgroundColor: '#111827',
    borderWidth: 1,
    borderColor: '#d4af37',
    borderRadius: 10,
    paddingVertical: 8,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  menuText: { color: '#f9fafb', fontSize: 15 },
  modalBackdropCenter: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.55)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  infoModal: {
    width: '100%',
    maxWidth: 440,
    backgroundColor: '#111827',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d4af37',
    padding: 16,
  },
  infoTitle: { color: '#f0e68c', fontSize: 18, fontWeight: '700', marginBottom: 10 },
  infoText: { color: '#e5e7eb', fontSize: 14, lineHeight: 20 },
  linkText: {
    color: '#93c5fd',
    fontSize: 14,
    marginBottom: 10,
    textDecorationLine: 'underline',
  },
  modalCloseButton: {
    marginTop: 12,
    alignSelf: 'flex-end',
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 8,
    backgroundColor: '#d4af37',
  },
  modalCloseButtonText: { color: '#111827', fontWeight: '700' },
  installButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 16,
    marginTop: 4,
    marginBottom: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
    backgroundColor: '#d4af37',
    borderRadius: 8,
  },
  installButtonText: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '700',
  },
});

export default styles;
