import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: 'transparent' },
  background: { flex: 1, width: '100%', height: '100%' },
  container: { flex: 1, padding: 16 },
  capsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'transparent',
    paddingVertical: 10,
    paddingHorizontal: 15,
    marginBottom: 16,
  },
  capsLabel: { color: '#000', fontSize: 18, fontWeight: 'bold' },
  capsButton: { backgroundColor: '#333', paddingVertical: 8, paddingHorizontal: 12, borderRadius: 5 },
  capsButtonText: { color: '#fff', fontSize: 14, fontWeight: 'bold' },
  capsValue: { color: '#000', fontSize: 20, fontWeight: 'bold', minWidth: 50, textAlign: 'center' },
  tableContainer: { flex: 1, backgroundColor: 'transparent', borderRadius: 8, overflow: 'hidden' },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#000',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  headerText: { color: '#fff', fontWeight: 'bold', fontSize: 14 },
  list: { flex: 1 },
  tableRow: {
    flexDirection: 'column',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
    backgroundColor: '#fff',
    borderStyle: 'dashed',
  },
  mainRowContent: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  itemNameContainer: { flex: 0.7, flexDirection: 'row', alignItems: 'center' },
  itemNameText: { fontSize: 16, fontWeight: 'bold', color: '#000', flexWrap: 'wrap' },
  equippedItemText: { fontStyle: 'italic', fontWeight: 'bold', color: '#005a9c' },
  itemSubRow: { flexDirection: 'row' },
  itemSubText: { fontSize: 12, color: '#666', marginRight: 15 },
  itemTypeIcon: { fontSize: 16, marginLeft: 6 },
  actionContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginBottom: 8,
  },
  actionButton: {
    backgroundColor: '#007BFF',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 5,
    marginRight: 8,
    marginBottom: 4,
  },
  sellButton: { backgroundColor: '#DC3545' },
  applyButton: { backgroundColor: '#28a745' },
  unequipButton: { backgroundColor: '#ffc107' },
  actionButtonText: { color: '#fff', fontSize: 12 },
  summaryContainer: {
    padding: 10,
    backgroundColor: 'rgba(0,0,0,0.5)',
    marginTop: 10,
    borderRadius: 5,
  },
  summaryText: { color: 'white', fontSize: 16, fontWeight: 'bold' },
  emptyListText: { textAlign: 'center', marginTop: 20, fontSize: 18, color: '#000' },
  footerActionsRow: { marginTop: 12, flexDirection: 'row', columnGap: 10 },
  addActionCell: {
    flex: 1,
    backgroundColor: 'rgba(0, 255, 0, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#333',
    borderStyle: 'dashed',
    borderRadius: 4,
  },
  addActionIcon: { fontSize: 24, color: '#000', fontWeight: 'bold', lineHeight: 26 },
  addActionLabel: { marginTop: 4, fontSize: 12, color: '#000', fontWeight: '600', textAlign: 'center' },
});

export default styles;
