import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '92%',
    maxWidth: 640,
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#5a5a5a',
  },
  modalTitle: {
    color: '#000',
    fontWeight: 'bold',
    fontSize: 16,
    marginBottom: 8,
  },
  filterPanel: {
    backgroundColor: 'rgb(245, 245, 245)',
    borderWidth: 1,
    borderColor: 'rgb(221, 221, 221)',
    borderRadius: 6,
    marginBottom: 8,
    paddingBottom: 0,
  },
  filterSpoilerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: 'rgb(245, 245, 245)',
  },
  filterSpoilerTitle: {
    color: '#000',
    fontWeight: 'bold',
  },
  filterSpoilerArrow: {
    color: '#000',
    fontWeight: 'bold',
  },
  filterSpoilerBody: {
    paddingHorizontal: 10,
    paddingBottom: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgb(221, 221, 221)',
  },
  searchInput: {
    borderWidth: 1,
    borderColor: '#5a5a5a',
    borderRadius: 4,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginTop: 8,
    marginBottom: 8,
    color: '#000',
    backgroundColor: '#fff',
  },
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  perkList: {
    maxHeight: 420,
    borderTopWidth: 1,
    borderTopColor: '#5a5a5a',
    paddingTop: 8,
    backgroundColor: '#fff',
  },
  filterItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 12,
    marginBottom: 6,
  },
  filterCheckbox: {
    width: 16,
    height: 16,
    borderWidth: 1,
    borderColor: '#5a5a5a',
    marginRight: 4,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  filterCheckboxChecked: {
    backgroundColor: '#16a34a',
    borderColor: '#15803d',
  },
  filterCheckMark: {
    color: '#fff',
    fontSize: 11,
    fontWeight: 'bold',
    lineHeight: 12,
  },
  filterLabel: {
    color: '#000',
    fontWeight: 'bold',
  },
  perkItem: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 6,
    marginBottom: 8,
    backgroundColor: '#fff',
  },
  perkDisabled: { backgroundColor: '#f1f5f9' },
  selectedPerk: { backgroundColor: '#299764' },
  selectedPerkName: { color: '#fff' },
  perkHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  perkNameCell: { flex: 1, paddingRight: 8 },
  perkRankCell: { flexShrink: 0, alignItems: 'flex-end' },
  perkName: { color: '#000', fontWeight: 'bold', textAlign: 'left' },
  perkRank: { color: '#000', fontWeight: 'bold', textAlign: 'right' },
  perkNameDisabled: { color: '#9aa1a9' },
  perkBody: { paddingHorizontal: 10, paddingBottom: 10 },
  perkDescription: { color: '#000', marginBottom: 8 },
  chooseButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#22c55e',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#16a34a',
  },
  chooseButtonDisabled: { backgroundColor: '#9ca3af', borderColor: '#9ca3af' },
  selectedChooseButton: { backgroundColor: '#ef4444', borderColor: '#b91c1c' },
  chooseButtonText: { color: '#fff', fontWeight: 'bold' },
  unmetContainer: { marginBottom: 8 },
  unmetText: { color: '#dc2626', marginBottom: 2 },
  modalButtons: {
    marginTop: 8,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  modalButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 4,
    borderWidth: 1,
    marginLeft: 8,
  },
  confirmButton: {
    backgroundColor: '#16a34a',
    borderColor: '#15803d',
    marginRight: 8,
  },
  removeButton: { backgroundColor: '#64748b', borderColor: '#475569' },
  cancelButton: { backgroundColor: '#ef4444', borderColor: '#b91c1c' },
  modalButtonText: { color: '#fff', fontWeight: 'bold' },
});

export default styles;
