import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, padding: 16, alignItems: 'center' },
  scrollView: { width: '100%' },
  scrollContent: { paddingBottom: 72 },
  sectionTitle: {
    color: '#fff',
    backgroundColor: '#1a1a1a',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#5a5a5a',
    borderRadius: 5,
    marginBottom: 8,
    marginTop: 8,
    overflow: 'hidden',
  },
  spoiler: { marginBottom: 8, width: '100%' },
  spoilerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2c2c2c',
    borderColor: '#5a5a5a',
    borderWidth: 1,
    borderRadius: 5,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  spoilerTitle: { flex: 1, color: '#fff', fontSize: 14, fontWeight: '600' },
  spoilerRank: { color: '#e8a33d', fontSize: 13, fontWeight: '700', marginLeft: 10 },
  spoilerArrow: { color: '#e8a33d', fontSize: 14, marginLeft: 10, fontWeight: '700' },
  spoilerBody: {
    marginTop: 8,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#5a5a5a',
    borderRadius: 5,
    padding: 12,
  },
  spoilerDescription: { color: '#000', fontSize: 14 },
  changeButton: {
    alignSelf: 'flex-start',
    marginTop: 12,
    backgroundColor: '#0ea5e9',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#0369a1',
  },
  changeButtonText: { color: '#fff', fontWeight: 'bold', fontSize: 13 },
  addPerkButton: {
    position: 'absolute',
    right: 16,
    bottom: 16,
    backgroundColor: '#0ea5e9',
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#0369a1',
  },
  addPerkButtonText: { color: '#fff', fontWeight: 'bold', fontSize: 14 },
});

export default styles;
