import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  background: {
    flex: 1,
    paddingHorizontal: 10,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'stretch',
  },
  statBoxContainer: {
    flex: 1,
    marginHorizontal: 4,
    borderWidth: 1,
    borderColor: '#5a5a5a',
    borderRadius: 5,
    flexDirection: 'column',
  },
  statBoxHeader: {
    backgroundColor: '#000',
    paddingVertical: 4,
    paddingHorizontal: 10,
    alignItems: 'center',
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
  },
  statBoxValueContainer: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    borderBottomLeftRadius: 4,
    borderBottomRightRadius: 4,
  },
  effectsListContainer: { width: '100%', marginTop: 4 },
  effectLineContainer: { marginBottom: 2, alignItems: 'center' },
  effectText: { fontSize: 12, fontWeight: '700', textAlign: 'center' },
  positiveEffectText: { color: '#00A651' },
  negativeEffectText: { color: '#D62828' },
  effectTimerText: { fontSize: 10, color: '#6B7280' },
  effectsPanelContainer: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#5a5a5a',
    borderRadius: 5,
    overflow: 'hidden',
  },
  effectsPanelHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#000',
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  effectsPanelTitle: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  effectsPanelToggle: {
    color: '#E8C84A',
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 22,
  },
  effectsPanelBody: {
    backgroundColor: '#fff',
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  effectsPanelEmpty: {
    fontSize: 12,
    color: '#888',
    textAlign: 'center',
    paddingVertical: 4,
  },
  effectsPanelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 3,
  },
  armorItemNameTitle: {
    color: '#fff',
    fontSize: 11,
    fontWeight: 'bold',
    marginTop: 2,
    paddingHorizontal: 4,
    textAlign: 'center',
    flexWrap: 'wrap',
    width: '100%',
  },
  armorPartContainer: { flex: 1, marginHorizontal: 4 },
  armorStatsContainer: {
    borderWidth: 1,
    borderColor: '#5a5a5a',
    borderTopWidth: 0,
    borderRadius: 5,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    overflow: 'hidden',
  },
  armorStatRow: { flexDirection: 'row', borderBottomColor: '#5a5a5a' },
  armorStatLabel: {
    color: '#000',
    fontSize: 13,
    flex: 1,
    padding: 5,
    backgroundColor: '#fce5cd',
  },
  armorStatValue: {
    color: '#000',
    fontWeight: 'bold',
    fontSize: 13,
    padding: 5,
    minWidth: 40,
    textAlign: 'center',
    borderLeftWidth: 1,
    borderLeftColor: '#5a5a5a',
    backgroundColor: '#fff',
  },
  weaponCardContainer: { flex: 1, marginHorizontal: 4 },
  emptyWeaponStats: {
    borderWidth: 1,
    borderColor: '#5a5a5a',
    borderTopWidth: 0,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#eee',
    minHeight: 100,
  },
  weaponStatRow: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#5a5a5a',
    borderTopWidth: 0,
    borderBottomWidth: 0,
  },
  weaponStatLabel: {
    backgroundColor: '#333',
    color: '#fff',
    fontWeight: 'bold',
    flex: 1,
    padding: 8,
    fontSize: 12,
  },
  weaponStatValue: {
    flex: 1,
    padding: 8,
    fontSize: 12,
    borderLeftWidth: 1,
    borderColor: '#5a5a5a',
    backgroundColor: '#fff',
    textAlign: 'center',
  },
  armorModificationButton: {
    padding: 8,
    minWidth: 40,
    borderLeftWidth: 1,
    borderColor: '#5a5a5a',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  armorModificationButtonText: { color: '#000', fontWeight: 'bold', fontSize: 13 },
  weaponModificationButton: {
    flex: 1,
    padding: 8,
    borderLeftWidth: 1,
    borderColor: '#5a5a5a',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  weaponModificationButtonText: { fontSize: 18, fontWeight: 'bold', color: '#333' },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  robotBodyModalContent: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 20,
    borderWidth: 1,
    borderColor: '#5a5a5a',
    alignItems: 'center',
  },
  robotBodyModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 10,
    textAlign: 'center',
  },
  robotBodyModalText: { fontSize: 16, marginBottom: 20, textAlign: 'center' },
  robotBodyModalButton: {
    backgroundColor: '#005A9C',
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 6,
  },
  robotBodyModalButtonText: { color: '#fff', fontWeight: '700' },
  weaponAmmoCellContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    borderLeftWidth: 1,
    borderColor: '#5a5a5a',
    backgroundColor: '#fff',
    paddingHorizontal: 6,
    paddingVertical: 4,
    gap: 6,
  },
  weaponAmmoBtn: {
    width: 26,
    height: 26,
    borderRadius: 4,
    backgroundColor: '#8b1a1a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  weaponAmmoBtnDisabled: { opacity: 0.35 },
  weaponAmmoBtnText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
    lineHeight: 20,
    includeFontPadding: false,
  },
  weaponAmmoCount: {
    flex: 1,
    textAlign: 'center',
    fontSize: 13,
    fontWeight: 'bold',
    color: '#222',
  },
});

export default styles;
