import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: 10,
    width: '90%',
    maxHeight: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  modalTitle: { fontSize: 18, fontWeight: 'bold' },
  closeButton: { padding: 5 },
  closeButtonText: { fontSize: 20, color: '#666' },
  modalBody: { padding: 15 },
  weaponInfo: {
    marginBottom: 20,
    padding: 10,
    backgroundColor: '#f5f5f5',
    borderRadius: 5,
  },
  weaponTitle: { fontSize: 16, fontWeight: 'bold', marginBottom: 5 },
  weaponStats: { fontSize: 12, color: '#666' },
  modificationsSection: { marginBottom: 20 },
  sectionTitle: { fontSize: 16, fontWeight: 'bold', marginBottom: 10 },
  collapsibleSection: { marginBottom: 10 },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
    backgroundColor: '#f0f0f0',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#ddd',
  },
  expandIcon: { fontSize: 16, color: '#666' },
  sectionContent: { paddingLeft: 10, paddingTop: 5 },
  modificationItem: {
    padding: 10,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 5,
    marginBottom: 5,
  },
  selectedModification: { borderColor: '#007AFF', backgroundColor: '#f0f8ff' },
  modificationName: { fontSize: 14, fontWeight: 'bold' },
  modificationCategory: { fontSize: 12, color: '#666', marginTop: 2 },
  modificationEffects: {
    fontSize: 12,
    color: '#333',
    marginTop: 5,
    flexWrap: 'wrap',
  },
  modificationStats: { fontSize: 11, color: '#666', marginTop: 3 },
  previewSection: { marginBottom: 20 },
  previewContent: { padding: 10, backgroundColor: '#e8f5e8', borderRadius: 5 },
  previewTitle: { fontSize: 16, fontWeight: 'bold', marginBottom: 5 },
  previewStats: { fontSize: 12, color: '#666', marginBottom: 5 },
  previewEffects: { fontSize: 12, color: '#333', marginBottom: 2 },
  previewQualities: { fontSize: 12, color: '#333' },
  modalFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 15,
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  cancelButton: {
    padding: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#ddd',
    flex: 1,
    marginRight: 10,
    alignItems: 'center',
  },
  cancelButtonText: { color: '#666' },
  applyButton: {
    padding: 10,
    borderRadius: 5,
    backgroundColor: '#007AFF',
    flex: 1,
    alignItems: 'center',
  },
  disabledButton: { backgroundColor: '#ccc' },
  applyButtonText: { color: 'white', fontWeight: 'bold' },
});

export default styles;
