import { StyleSheet, Platform } from 'react-native';

// Скошенный левый верхний угол таба: на web — clip-path, на native — скругление.
const BEVELED_TAB = Platform.OS === 'web'
  ? { clipPath: 'polygon(10px 0, 100% 0, 100% 100%, 0 100%, 0 10px)' }
  : { borderTopLeftRadius: 8 };

const styles = StyleSheet.create({
  background: {
    flex: 1,
    paddingHorizontal: 10,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'stretch',
  },
  statBoxContainer: {
    flex: 1,
    marginHorizontal: 4,
    borderWidth: 1,
    borderColor: '#5a5a5a',
    borderRadius: 5,
    flexDirection: 'column',
  },
  statBoxHeader: {
    backgroundColor: '#000',
    paddingVertical: 4,
    paddingHorizontal: 10,
    alignItems: 'center',
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
  },
  statBoxValueContainer: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    borderBottomLeftRadius: 4,
    borderBottomRightRadius: 4,
  },
  effectsListContainer: { width: '100%', marginTop: 4 },
  effectLineContainer: { marginBottom: 2, alignItems: 'center' },
  effectText: { fontSize: 12, fontWeight: '700', textAlign: 'center' },
  positiveEffectText: { color: '#00A651' },
  negativeEffectText: { color: '#D62828' },
  effectTimerText: { fontSize: 10, color: '#6B7280' },
  effectsPanelContainer: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#5a5a5a',
    borderRadius: 5,
    overflow: 'hidden',
  },
  effectsPanelHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#000',
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  effectsPanelTitle: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  effectsPanelToggle: {
    color: '#E8C84A',
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 22,
  },
  effectsPanelBody: {
    backgroundColor: '#fff',
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  effectsPanelEmpty: {
    fontSize: 12,
    color: '#888',
    textAlign: 'center',
    paddingVertical: 4,
  },
  effectsPanelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 3,
  },
  armorItemNameTitle: {
    color: '#fff',
    fontSize: 11,
    fontWeight: 'bold',
    marginTop: 2,
    paddingHorizontal: 4,
    textAlign: 'center',
    flexWrap: 'wrap',
    width: '100%',
  },
  armorPartContainer: { flex: 1, marginHorizontal: 4 },
  armorStatsContainer: {
    borderWidth: 1,
    borderColor: '#5a5a5a',
    borderTopWidth: 0,
    borderRadius: 5,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    overflow: 'hidden',
  },
  armorStatRow: { flexDirection: 'row', borderBottomColor: '#5a5a5a' },
  armorStatLabel: {
    color: '#000',
    fontSize: 13,
    flex: 1,
    padding: 5,
    backgroundColor: '#fce5cd',
  },
  armorStatValue: {
    color: '#000',
    fontWeight: 'bold',
    fontSize: 13,
    padding: 5,
    minWidth: 40,
    textAlign: 'center',
    borderLeftWidth: 1,
    borderLeftColor: '#5a5a5a',
    backgroundColor: '#fff',
  },
  weaponCardContainer: { flex: 1, marginHorizontal: 4 },
  emptyWeaponStats: {
    borderWidth: 1,
    borderColor: '#5a5a5a',
    borderTopWidth: 0,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#eee',
    minHeight: 100,
  },
  weaponStatRow: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#5a5a5a',
    borderTopWidth: 0,
    borderBottomWidth: 0,
  },
  weaponStatLabel: {
    backgroundColor: '#333',
    color: '#fff',
    fontWeight: 'bold',
    flex: 1,
    padding: 8,
    fontSize: 12,
  },
  weaponStatValue: {
    flex: 1,
    padding: 8,
    fontSize: 12,
    borderLeftWidth: 1,
    borderColor: '#5a5a5a',
    backgroundColor: '#fff',
    textAlign: 'center',
  },
  armorModificationButton: {
    padding: 8,
    minWidth: 40,
    borderLeftWidth: 1,
    borderColor: '#5a5a5a',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  armorModificationButtonText: { color: '#000', fontWeight: 'bold', fontSize: 13 },
  weaponModificationButton: {
    flex: 1,
    padding: 8,
    borderLeftWidth: 1,
    borderColor: '#5a5a5a',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  weaponModificationButtonText: { fontSize: 18, fontWeight: 'bold', color: '#333' },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  robotBodyModalContent: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 20,
    borderWidth: 1,
    borderColor: '#5a5a5a',
    alignItems: 'center',
  },
  robotBodyModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 10,
    textAlign: 'center',
  },
  robotBodyModalText: { fontSize: 16, marginBottom: 20, textAlign: 'center' },
  robotBodyModalButton: {
    backgroundColor: '#005A9C',
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 6,
  },
  robotBodyModalButtonText: { color: '#fff', fontWeight: '700' },
  weaponAmmoCellContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    borderLeftWidth: 1,
    borderColor: '#5a5a5a',
    backgroundColor: '#fff',
    paddingHorizontal: 6,
    paddingVertical: 4,
    gap: 6,
  },
  // Прочность части силовой брони — ДВЕ строки во всю ширину ячейки, рендерятся
  // внутри контейнера ячейки (footer ArmorPart), не отдельно (ПРАВИЛО владельца):
  // заголовок «Прочность (ОЗ)» белым шрифтом на тёмном фоне + строка счётчика.
  paDurabilityBlock: {
    width: '100%',
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderColor: '#5a5a5a',
  },
  paDurabilityHeaderRow: {
    width: '100%',
    backgroundColor: '#333',
    paddingVertical: 4,
    alignItems: 'center',
  },
  paDurabilityHeader: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 12,
  },
  paDurabilityCounterRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 6,
  },
  // Значение счётчика — как armorStatValue, но БЕЗ левой границы (ПРАВИЛО
  // владельца: у значений каунтера левой границы нет, строка единообразная).
  paDurabilityValue: {
    color: '#000',
    fontWeight: 'bold',
    fontSize: 13,
    padding: 5,
    minWidth: 40,
    textAlign: 'center',
  },
  weaponAmmoBtn: {
    width: 26,
    height: 26,
    borderRadius: 4,
    backgroundColor: '#8b1a1a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  weaponAmmoBtnDisabled: { opacity: 0.35 },
  weaponAmmoBtnText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
    lineHeight: 20,
    includeFontPadding: false,
  },
  weaponAmmoCount: {
    flex: 1,
    textAlign: 'center',
    fontSize: 13,
    fontWeight: 'bold',
    color: '#222',
  },

  // ── Режимы отображения карточек оружия: спойлеры и табы ────────────────

  weaponSpoiler: { marginBottom: 8 },
  weaponSpoilerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2c2c2c',
    borderColor: '#5a5a5a',
    borderWidth: 1,
    borderRadius: 5,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  weaponSpoilerTitle: { flex: 1, color: '#fff', fontSize: 14, fontWeight: '600' },
  weaponSpoilerArrow: { color: '#e8a33d', fontSize: 14, marginLeft: 10, fontWeight: '700' },
  weaponSpoilerBody: { alignItems: 'center', marginTop: 8 },
  weaponSpoilerCard: { width: '66.67%' },

  // Тулбар оружия: слева тумблер рукопашной атаки (ладонь), справа —
  // переключатель раскладки (линии = спойлеры, две черты = карточки).
  weaponDisplayToggleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  weaponDisplayToggleGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  weaponDisplayToggleBtn: {
    width: 38,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2c2c2c',
    borderWidth: 1,
    borderColor: '#5a5a5a',
    borderRadius: 5,
  },
  weaponDisplayToggleBtnActive: {
    borderColor: '#e8a33d',
    backgroundColor: '#4a4a4a',
  },

  // Третий режим (табы) скрыт из переключателя, но стили рендера сохранены.
  weaponTabsRow: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 10, gap: 6 },
  weaponTab: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#2c2c2c',
    borderColor: '#5a5a5a',
    borderWidth: 1,
    ...BEVELED_TAB,
  },
  weaponTabActive: { backgroundColor: '#4a4a4a', borderColor: '#e8a33d' },
  weaponTabText: { color: '#aaa', fontSize: 13 },
  weaponTabTextActive: { color: '#fff', fontWeight: '700' },
  weaponTabsStage: { flexDirection: 'row', alignItems: 'center' },
  weaponTabNavArrow: {
    color: '#e8a33d',
    fontSize: 20,
    fontWeight: '700',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  weaponTabNavArrowDisabled: { opacity: 0.25 },
  weaponTabCardWrap: { flex: 1, alignItems: 'center' },
  weaponTabCard: { width: '66.67%' },
});

export default styles;
